<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 04 - Filtragem: passa-baixa e passa-alta</title>
  <meta name="description" content="Capítulo 04 - Filtragem: passa-baixa e passa-alta" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 04 - Filtragem: passa-baixa e passa-alta" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 04 - Filtragem: passa-baixa e passa-alta" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var subtitles = document.querySelectorAll("h1 + .subtitle");
  subtitles.forEach(function(subtitle) {
    var h1 = subtitle.previousElementSibling;
    h1.insertAdjacentElement('afterend', subtitle);
  });
});
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path=""><a href="#capítulo-04---filtragem-passa-baixa-e-passa-alta"><i class="fa fa-check"></i><b>1</b> Capítulo 04 - Filtragem: passa-baixa e passa-alta</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#introdução"><i class="fa fa-check"></i><b>1.1</b> Introdução</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#filtragem-passa-baixa-e-passa-alta-em-r"><i class="fa fa-check"></i><b>1.2</b> Filtragem passa-baixa e passa-alta em R</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#referências-bibliográficas"><i class="fa fa-check"></i><b>1.3</b> Referências Bibliográficas</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Capítulo 04 - Filtragem: passa-baixa e passa-alta</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Capítulo 04 - Filtragem: passa-baixa e passa-alta</h1>
<h2 class="subtitle"><em>Processamento Digital de Imagens Orbitais</em></h2>
</div>
<div id="capítulo-04---filtragem-passa-baixa-e-passa-alta" class="section level1 hasAnchor" number="1" style="text-align: justify;">
<h1><span class="header-section-number">1</span> Capítulo 04 - Filtragem: passa-baixa e passa-alta<a href="#capítulo-04---filtragem-passa-baixa-e-passa-alta" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introdução" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Introdução<a href="#introdução" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Em se tratando das informações colorimétricas de cada um dos pixels que compõem a imagem orbital, é possível realizar diversos tipos de ajustes nas imagens para realçar ou suprimir determinadas características. A seguir são apresentadas algumas técnicas comuns relacionadas a isso:</p>
<ul>
<li><p>Filtragem passa-alta (realce de bordas): este filtro destaca as transições abruptas de intensidade na imagem, realçando bordas e detalhes. O efeito é obtido subtraindo a versão “borrada” da imagem da imagem original.</p></li>
<li><p>Filtragem passa-baixa (suavização): reduz o contraste entre as intensidades dos pixels, suavizando a imagem. Um exemplo é a aplicação de uma média ponderada para suavizar detalhes finos.</p></li>
<li><p>Equalização de histograma: esta técnica redistribui as intensidades dos pixels na imagem para melhor utilizar a faixa dinâmica disponível, aumentando o contraste.</p></li>
<li><p>Ajuste de brilho e contraste: modificar globalmente o brilho e o contraste da imagem pode ajudar a realçar ou suprimir características.</p></li>
<li><p>Segmentação: dividir a imagem em regiões com base em critérios de intensidade pode destacar áreas de interesse.</p></li>
<li><p>Transformações morfológicas: operações como erosão e dilatação podem ser usadas para realçar ou suprimir determinados padrões.</p></li>
</ul>
<p>A escolha da técnica dependerá do objeto da análise e das características desejadas na imagem. É possível experimentar diferentes abordagens e avaliar os resultados visualmente para determinar qual método atende melhor às necessidades.</p>
<p>Trabalhar com processamento de imagem no R envolve o uso de bibliotecas especificas, tais como raster, rgdal e EBImage, as quais fornecem funcionalidades para manipular e processar imagens. Outro aspecto relevante resguarda o recorte das imagens orbitais antes do carregamento no R, o que facilita a análise, economiza tempo e recursos computacionais. Para escolher a área de interesse é importante certificar-se de manter características relevantes para a análise que se pretende.</p>
</div>
<div id="filtragem-passa-baixa-e-passa-alta-em-r" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Filtragem passa-baixa e passa-alta em R<a href="#filtragem-passa-baixa-e-passa-alta-em-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Na aula de hoje iremos precisar dos pacotes a seguir. Então, antes de iniciar, realizem a instalação dos pocotes e o carregamento dos mesmos, como instruído no código a seguir.</p>
<p>Antes de darmos início ao trabalho, vamos conferir se estamos trabalhando no diretório correto (pasta de trabalho).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co">#conferindo o diretório de trabalho</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
<pre><code>## [1] &quot;C:/ARQUIVOS COMPUTADOR/DOUTORADO/EBOOK PROCESSAMENTO DIGITAL DE IMAGENS&quot;</code></pre>
<p>Com os pacotes instalados e carregados, vamos carregar a imagem orbital para prática de hoje, referente a uma área de interesse recortada no MultiSpec. A imagem orbital original é aquela que usamos nas práticas anteriores (proveniente do acervo do INPE), aqui focaremos em uma área menor para reduzir o número de pixels na nossa análise. Portanto, utilizaremos o arquivo <strong>area_de_interesse.tif</strong> e para o carregamento aplicaremos a função será <em>raster()</em>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co">#Carregamento da imagem orbital</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>area_de_interesse <span class="ot">&lt;-</span> <span class="fu">raster</span>(<span class="st">&quot;area_de_interesse.tif&quot;</span>)</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="fu">plot</span>(area_de_interesse, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Orginal da area de interesse&quot;</span>)</span></code></pre></div>
<p><img src="cap04_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Com a imagem carregada, vamos dividir nosso processo de acordo com os filtros tratados na introdução. O primeiro será o passa alta. Para realizar a filtragem passa-alta, primeiro precisamos extrair os valores dos pixels da imagem. Em seguida, aplicamos um filtro que destaca as variações de intensidade, ou seja, realça as bordas e os detalhes da imagem. Este processo envolve a aplicação de uma máscara de convolução na imagem.</p>
<p>Para começar, podemos usar a função <strong>as.matrix</strong> para converter a imagem raster em uma matriz e então aplicar a filtragem passa-alta usando uma máscara apropriada. Vamos prosseguir com a extração dos valores colorimétricos e a aplicação do filtro passa-alta.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># Converter a imagem em uma matriz</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>matriz_pixels <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(area_de_interesse)</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a><span class="co"># Verificar as dimensões da matriz (altura x largura x número de canais)</span></span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a><span class="fu">dim</span>(matriz_pixels)</span></code></pre></div>
<pre><code>## [1] 753 737</code></pre>
<p>Através do resultado da função <em>dim()</em>, observamos que a imagem tem dimensões de 753 pixels de altura por 737 pixels de largura. Agora podemos continuar aplicando o filtro passa-alta. Vamos definir uma máscara de convolução apropriada para realçar as bordas e detalhes na imagem. Posteriormente, vamos criar uma função para que a convolução seja aplicada a cada um dos pixels da imagem que estamos analisando. Após a criação da máscara de convolução, vamos aplicá-la a imagem referente a nossa área de interesse.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># Definir uma máscara de convolução para filtragem passa-alta</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>mascara_passa_alta <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">8</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a><span class="co"># Criar uma função para aplicar a convolução</span></span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>filtro_passa_alta <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>  <span class="fu">sum</span>(x <span class="sc">*</span> mascara_passa_alta)</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>}</span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" tabindex="-1"></a><span class="co"># Aplicar a filtragem passa-alta usando a função focal</span></span>
<span id="cb6-10"><a href="#cb6-10" tabindex="-1"></a>img_filtrada_passaalta <span class="ot">&lt;-</span> <span class="fu">focal</span>(area_de_interesse, <span class="at">w =</span> mascara_passa_alta, <span class="at">fun =</span> filtro_passa_alta)</span></code></pre></div>
<p>Após a filtragem passa-alta da imagem orbrital que estamos trabalhando, vamos comparar o resultado obtido.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="fu">plot</span>(area_de_interesse, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Original&quot;</span>)</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a><span class="fu">plot</span>(img_filtrada_passaalta, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Filtrada (Passa-Alta)&quot;</span>)</span></code></pre></div>
<p><img src="cap04_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>No segundo momento, vamos aplicar a filtragem passa-baixa usando a técnica da média. Isso suavizará a imagem, removendo detalhes finos e ruídos. A filtragem passa-baixa de média consiste em substituir o valor de cada pixel na imagem pela média dos valores dos pixels em sua vizinhança. Vamos definir o tamanho da vizinhança (também chamado de tamanho do kernel) e calcular a média para cada pixel. Depois vamos criar a função para a filtragem passa-baixa de média e na sequência realizar a filtragem</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># Definir o tamanho do kernel para a filtragem passa-baixa de média</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>tamanho_kernel <span class="ot">&lt;-</span> <span class="dv">3</span>  <span class="co"># Por exemplo, um kernel de 3x3</span></span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a><span class="co"># Função para realizar a filtragem passa-baixa de média</span></span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>filtro_passa_baixa_media <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">mean</span>(x))</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>}</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a><span class="co"># Aplicar a filtragem passa-baixa usando a função focal</span></span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a>img_filtrada_passabaixamedia <span class="ot">&lt;-</span> <span class="fu">focal</span>(area_de_interesse, <span class="at">w =</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="at">nrow =</span> tamanho_kernel, <span class="at">ncol =</span> tamanho_kernel), <span class="at">fun =</span> filtro_passa_baixa_media)</span></code></pre></div>
<p>Agora vamos comparar nossa imagem original à imagem filtrada pela passa-baixa de média</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a><span class="fu">plot</span>(area_de_interesse, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Original&quot;</span>)</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a><span class="fu">plot</span>(img_filtrada_passabaixamedia, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Filtrada (Passa-Baixa de Media)&quot;</span>)</span></code></pre></div>
<p><img src="cap04_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>E finalmente vamos focar no filtro passa-baixa de mediana. Essa técnica é útil para remover ruídos da imagem, preservando melhor as bordas e detalhes do que a filtragem passa-baixa de média. Para realizar a filtragem passa-baixa de mediana, vamos definir uma vizinhança em torno de cada pixel, calcular a mediana dos valores dos pixels nessa vizinhança e atribuir esse valor ao pixel central. Vamos usar a função <em>focal()</em> do pacote raster para aplicar a filtragem. Para tal, vamos reutizar <strong>tamanho_kernel &lt;- 3</strong> para a função. Posteriormente vamos construir a função para a filtragem e, na sequência, filtrar nossa imagem original.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="co"># Função para realizar a filtragem passa-baixa de mediana</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>filtro_passa_baixa_mediana <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">median</span>(x))</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>}</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a><span class="co"># Aplicar a filtragem passa-baixa usando a função focal</span></span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>img_filtrada_passabaixa_mediana <span class="ot">&lt;-</span> <span class="fu">focal</span>(area_de_interesse, <span class="at">w =</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="at">nrow =</span> tamanho_kernel, <span class="at">ncol =</span> tamanho_kernel), <span class="at">fun =</span> filtro_passa_baixa_mediana)</span></code></pre></div>
<p>Agora vamos comparar nossa imagem original à imagem filtrada pela passa-baixa de mediana</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">plot</span>(area_de_interesse, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Original&quot;</span>)</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a><span class="fu">plot</span>(img_filtrada_passabaixa_mediana, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem Filtrada (Passa-Baixa de Mediana)&quot;</span>)</span></code></pre></div>
<p><img src="cap04_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Com isso, encerramos nossa prática sobre filtragem passa-alta, passa-baixa de média e passa baixa de mediana. Vimos como estes filtros podem ser aplicados no R e como as imagens geradas são filtradas. Até a próxima aula.</p>
<p><a href="apresentação.html">Índice</a></p>
<p><a href="capítulo-03---histogramas---quantização-e-amostragem.html">Capítulo 03 - Histogramas - Quantização e Amostragem</a></p>
<p><a href="capítulo-05---morfologia-matemática.html">Capítulo 05 - Morfologia Matemática</a></p>
</div>
<div id="referências-bibliográficas" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Referências Bibliográficas<a href="#referências-bibliográficas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ANDERSON, E. C. Making Maps with R Â: Reproducible Research. GitHub, 2021. Disponível em: <a href="https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html" class="uri">https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html</a>.</p>
<p>CHAMBERS, J. M. Extending R. CRC Press, 364p., 2017. ISBN: 9781498775724.</p>
<p>DA SILVA, F. R.; GONÇALVES-SOUZA, T.; PATERNO, G. B.; PROVETE, D. B.; VANCINE, M. H. Análises ecológicas no R. Recife, PE: Nupeea, 1ª ed., 640p., 2022. ISBN: 9788579175640. Disponível em: <a href="https://analises-ecologicas.com/" class="uri">https://analises-ecologicas.com/</a>.</p>
<p>GAUTHIER, N. Anthromes 12K DGG (V1) analysis code and R research compendium. Harvard Dataverse, 2021. DOI: <a href="https://doi.org/10.7910/DVN/6FWPZ9" class="uri">https://doi.org/10.7910/DVN/6FWPZ9</a>.</p>
<p>LOVELACE, R. Introduction to visualizing spatial data in R. 2017. Disponível em:<a href="https://github.com/Robinlovelace/Creating-maps-in-R" class="uri">https://github.com/Robinlovelace/Creating-maps-in-R</a>.</p>
<p>LOVELACE, R., NOWOSAD, J., &amp; MUENCHOW, J. Geocomputation with R. Chapman and Hall/CRC, 353p., 2019. Disponível em: <a href="https://www.routledge.com/Geocomputation-withR/Lovelace-Nowosad-Muenchow/p/book/9780367670573" class="uri">https://www.routledge.com/Geocomputation-withR/Lovelace-Nowosad-Muenchow/p/book/9780367670573</a></p>
<p>MACHLIS, S. Create maps in R in 10 (fairly) easy steps. Computerworld, 2017. Disponível em: <a href="https://www.computerworld.com/article/3038270/create-maps-in-r-in-10-fairly-easy-steps.html" class="uri">https://www.computerworld.com/article/3038270/create-maps-in-r-in-10-fairly-easy-steps.html</a>.</p>
<p>MARTOS, G. Cluster Analysis with R. 2021. Disponível em: <a href="https://rstudio-pubsstatic.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html" class="uri">https://rstudio-pubsstatic.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html</a>.</p>
<p>MENESES, P. R.; ALMEIDA, T. D.; ROSA, A. N. D. C. S.; SANO, E. E. et al. Introdução ao Processamento de Imagens de Sensoriamento Remoto. Brasília: UnB-CNPq, 276 p., 2012.</p>
<p>MORENO, M. &amp; BASILLE, M. Drawing beautiful maps programmatically with R, sf and ggplot2 - Part 1: Basics. 2021. Disponível em: <a href="https://r-spatial.org/r/2018/10/25/ggplot2-sf.html" class="uri">https://r-spatial.org/r/2018/10/25/ggplot2-sf.html</a>.</p>
<p>MUENCHOW, J.; SCHRATZ, P.; BRENNING, A. RQGIS: Integrating R with QGIS for Statistical Geocomputing. The R Journal, 9, n. 2, p. 409-428, 2017 2017. Doi: <a href="https://doi.org/10.32614/RJ-2017-067" class="uri">https://doi.org/10.32614/RJ-2017-067</a>.</p>
<p>NOVIA, D. Cluster Analysis in R: Tips for Great Analysis and Visualization. Datanovia, 2018.Disponível em: <a href="https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/" class="uri">https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/</a>.</p>
<p>PEBESMA, E.; BIVAND, R. Spatial Data Science: With Applications in R. Chapman and Hall/CRC, 1ª ed., 314p., 2023. Doi: <a href="https://doi.org/10.1201/9780429459016" class="uri">https://doi.org/10.1201/9780429459016</a>.</p>
<p>R-BLOGGERS. Cluster Analysis in R. 2021. Disponível em: <a href="https://www.rbloggers.com/2021/04/cluster-analysis-in-r/" class="uri">https://www.rbloggers.com/2021/04/cluster-analysis-in-r/</a>.</p>
<p>STANIAK, M.; BIECEK, P. The Landscape of R Packages for Automated Exploratory Data Analysis. The R Journal, v. 11, n. 2, 23 p., 2019. Disponível em: <a href="https://arxiv.org/pdf/1904.02101" class="uri">https://arxiv.org/pdf/1904.02101</a>.</p>
<p>VENABLES, W. N.; SMITH, D. M. An Introduction to R. R Core Team, 2017. Disponível em: <a href="http://colinfay.me/intro-to-r/#" class="uri">http://colinfay.me/intro-to-r/#</a>.</p>
<p>WICKHAM, H. Advanced R. CRC Press, 2ª ed., 2022. Disponível em: <a href="https://advr.hadley.nz/#license" class="uri">https://advr.hadley.nz/#license</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
