---
title: "Processamento Digital de Imagens Orbitais (PDI) em R"
author: "Maximiliano Gobbo"
date: "2024-01-12"
output:
  bookdown::gitbook:
    css: style.css
    config:
      toc:
        collapse: section
        before: | 
          <li><a href="./">Início</a></li>
      navbar:
        title: "Apostila PDI em R"
rmd_files:
  - "index.Rmd"
  - "cap01.Rmd"
  - "cap02.Rmd"
  - "cap03.Rmd"
  - "cap04.Rmd"
  - "cap05.Rmd"
  - "cap06.Rmd"
  - "cap07.Rmd"
  - "cap08.Rmd"
  - "cap09.Rmd"  
html_files:
  - "index.html"
  - "capítulo-01---introdução-ao-r-rstudio-e-rmarkdown.html"
  - "capítulo-02---classificação-de-imagens-orbitais.html"
  - "capítulo-03---histogramas---quantização-e-amostragem.html"
  - "capítulo-04---filtragem-passa-baixa-e-passa-alta.html"
  - "capítulo-05---morfologia-matemática.html"
  - "capítulo-06---transformação-no-espaço-imagem.html"
  - "capítulo-07---aritmética-de-bandas-soma-subtração-multiplicação-e-divisão.html"
  - "capítulo-08---correção-geométrica-e-registro-de-imagens.html"
  - "capítulo-09---fusão-de-imagens.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div style="text-align: justify;">

# Index

O livro Processamento Digital de Imagens (PDI) com R foi desenvolvido durante a disciplina de PDI, realizada na Universidade Federal de Uberlândia (UFU) para o curso de Geografia (Instituto de Geografia). No livro são apresentadas diferentes ferramentas para a análise, tratamento e manipulação de imagens orbitais. A base teórica para sua construção foi o livro de Meneses et al. (2012): Introdução ao Processamento de Imagens de Sensoriamento Remoto. 

Vale destacar que nosso foco foi transpor procedimentos executados em softwares de PDI para o universo da programação, mais propriamente ao Software R. Por tal, ao início de cada capítulo do nosso livro fazemos menção ao(s) capítulo(s) do livro de Meneses et al. (2012), de modo que nosso leitor possa complementar a compreensão dos procedimentos com esta formidável base teórica. 

Os dados vetoriais e raster, as imagens orbitais originais e recortadas e outros documentos utilizados neste livro foram captados de bases e plataformas globais, como o Instituto Nacional de Pesquisas Espaciais (INPE-Brasil), o Instituto Brasileiro de Geografia e Estatística (IBGE-Brasil) e o Copernicus. 

Esperamos que o livro Processamento Digital de Imagens em R possa ilustrar alguns dos inúmeros procedimentos associados ao Processamento Digital de Imagem. Além disso, pretendemos demonstrar o poder analítico do Software R, trazendo de forma didática e dinâmica como a programação pode ser um recurso diferencial no geoprocessamento e em seus desdobramentos.

## Sumário

0. [Índice](index.html)
1. [Capítulo 01 - Introdução ao R, RStudio e RMarkdown](capítulo-01---introdução-ao-r-rstudio-e-rmarkdown.html)
2. [Capítulo 02 - Classificação de Imagens Orbitais](capítulo-02---classificação-de-imagens-orbitais.html)
3. [Capítulo 03 - Histogramas - Quantização e Amostragem](capítulo-03---histogramas---quantização-e-amostragem.html)
4. [Capítulo 04 - Filtragem: passa-baixa e passa-alta](capítulo-04---filtragem-passa-baixa-e-passa-alta.html)
5. [Capítulo 05 - Morfologia Matemática](capítulo-05---morfologia-matemática.html)
6. [Capítulo 06 - Transformação no Espaço Imagem](capítulo-06---transformação-no-espaço-imagem.html)
7. [Capítulo 07 - Aritmética de Bandas: soma, subtração, multiplicação e divisão](capítulo-07---aritmética-de-bandas-soma-subtração-multiplicação-e-divisão.html)
8. [Capítulo 08 - Correção Geométrica e Registro de Imagens](capítulo-08---correção-geométrica-e-registro-de-imagens.html)
9. [Capítulo 09 - Fusão de Imagens](capítulo-09---fusão-de-imagens.html)


## Sobre o autor

**Maximliano S. L. A. Gobbo:** Doutorando do Programa de Pós-Graduação em Biotecnologia no Instituto Nacional de Metrologia Qualidade e Tecnologia (INMETRO) na condição de bolsista CAPES, desenvolvendo a Tese de Doutorado intitulada “Regionalização dos Antromas Brasileiros: Ferramenta para o Mapeamento em Linguagem R®”, sob orientação do Prof. Dr. Thiago de Oliveira Araujo e da Profa. Dra. Claudia de Oliveira Faria Salema. Mestre em Metrologia e Qualidade pelo INMETRO (bolsista PRONAMETRO) com a dissertação " Regionalização dos Antromas Brasileiros: Ferramentas Metrológicas para Garantia da Qualidade de Resultados Demográficos e de Uso e Cobertura dos Solos", sob orientação do Prof. Dr. Thiago de Oliveira Araujo e Profa. Dra. Claudia de Oliveira Faria Salema. Pós-graduado (especialização) em Perícia e Auditoria Ambiental pelo Centro Universitário Internacional (UNINTER), atuando junto a Empresas de Consultoria e Assessoria Ambiental e compondo o Cadastro de Auxiliares de Justiça do STJ-SP, nas áreas de Biologia e Ciências Ambientais. Graduado em Ciências Biológicas, modalidades Licenciatura e Bacharelado, pela Universidade Federal de Uberlândia (UFU). Participou do Programa Ciência sem Fronteiras, financiado pela CAPES, na cidade de Roma – Itália, onde desenvolveu o projeto de pesquisa “A Interferência de Fatores do Bioma Antropomórfico Urbano na expressão da Hipertensão” no Laboratório de Ecologia Humana da Università degli Studi di Roma “Tor Vergata” e finalizado no Instituto de Ciências Biomédicas da Universidade Federal de Uberlândia. Atuou como bolsista da Pró-Reitoria de Graduação da Universidade Federal de Uberlândia, desenvolvendo atividades Escola de Educação Básica (ESEBA) no projeto “Apoio aos Laboratórios de Ensino de Ciências”, participando da organização, catalogação e manutenção dos espaços, bem como na produção de novos recursos didáticos, como laminário didático comparativo de tecidos e células animais e vegetais e o modelo molecular para ensino de química. Possui experiência em Educação, adquirida enquanto membro do Programa Institucional de Bolsas de Iniciação à Docência (PIBID) nos projetos Ciências da Natureza e Biologia, ambos vinculados ao Instituto de Biologia da UFU. Foi monitor das disciplinas de Sistemática de Criptógamas e Educação Ambiental. Desenvolveu atividades de acompanhamento pedagógico junto a um Abrigo Institucional de crianças e adolescentes, promovendo atividades que mediam o processo ensino-aprendizagem e capacitação dos educadores da unidade.

## Referências Bibliográficas

ANDERSON, E. C. Making Maps with R Â: Reproducible Research. GitHub, 2021. Disponível em: https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html.

CHAMBERS, J. M. Extending R. CRC Press, 364p., 2017. ISBN: 9781498775724.

DA SILVA, F. R.; GONÇALVES-SOUZA, T.; PATERNO, G. B.; PROVETE, D. B.; VANCINE, M. H. Análises ecológicas no R. Recife, PE: Nupeea, 1ª ed., 640p., 2022. ISBN: 9788579175640. Disponível em: https://analises-ecologicas.com/.

GAUTHIER, N. Anthromes 12K DGG (V1) analysis code and R research compendium. Harvard Dataverse, 2021. DOI: https://doi.org/10.7910/DVN/6FWPZ9.

LOVELACE, R. Introduction to visualizing spatial data in R. 2017. Disponível em:https://github.com/Robinlovelace/Creating-maps-in-R.

LOVELACE, R., NOWOSAD, J., & MUENCHOW, J. Geocomputation with R. Chapman and Hall/CRC, 353p., 2019. Disponível em: https://www.routledge.com/Geocomputation-withR/Lovelace-Nowosad-Muenchow/p/book/9780367670573

MACHLIS, S. Create maps in R in 10 (fairly) easy steps. Computerworld, 2017. Disponível em: https://www.computerworld.com/article/3038270/create-maps-in-r-in-10-fairly-easy-steps.html.

MARTOS, G. Cluster Analysis with R. 2021. Disponível em: https://rstudio-pubsstatic.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html.

MENESES, P. R.; ALMEIDA, T. D.; ROSA, A. N. D. C. S.; SANO, E. E. et al. Introdução ao Processamento de Imagens de Sensoriamento Remoto. Brasília: UnB-CNPq, 276 p., 2012.

MORENO, M. & BASILLE, M. Drawing beautiful maps programmatically with R, sf and ggplot2 - Part 1: Basics. 2021. Disponível em: https://r-spatial.org/r/2018/10/25/ggplot2-sf.html.

MUENCHOW, J.; SCHRATZ, P.; BRENNING, A. RQGIS: Integrating R with QGIS for Statistical Geocomputing. The R Journal, 9, n. 2, p. 409-428, 2017 2017. Doi: https://doi.org/10.32614/RJ-2017-067.

NOVIA, D. Cluster Analysis in R: Tips for Great Analysis and Visualization. Datanovia, 2018.Disponível em: https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/.

PEBESMA, E.; BIVAND, R. Spatial Data Science: With Applications in R. Chapman and Hall/CRC, 1ª ed., 314p., 2023. Doi: https://doi.org/10.1201/9780429459016.

R-BLOGGERS. Cluster Analysis in R. 2021. Disponível em: https://www.rbloggers.com/2021/04/cluster-analysis-in-r/.

STANIAK, M.; BIECEK, P. The Landscape of R Packages for Automated Exploratory Data Analysis. The R Journal, v. 11, n. 2, 23 p., 2019. Disponível em: https://arxiv.org/pdf/1904.02101.

VENABLES, W. N.; SMITH, D. M. An Introduction to R. R Core Team, 2017. Disponível em: http://colinfay.me/intro-to-r/#.

WICKHAM, H. Advanced R. CRC Press, 2ª ed., 2022. Disponível em: https://advr.hadley.nz/#license

</div>