<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 06 - Transformação no Espaço Imagem</title>
  <meta name="description" content="Capítulo 06 - Transformação no Espaço Imagem" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 06 - Transformação no Espaço Imagem" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 06 - Transformação no Espaço Imagem" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var subtitles = document.querySelectorAll("h1 + .subtitle");
  subtitles.forEach(function(subtitle) {
    var h1 = subtitle.previousElementSibling;
    h1.insertAdjacentElement('afterend', subtitle);
  });
});
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path=""><a href="#capítulo-06---transformação-no-espaço-imagem"><i class="fa fa-check"></i><b>1</b> Capítulo 06 - Transformação no Espaço Imagem</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#introdução"><i class="fa fa-check"></i><b>1.1</b> Introdução</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#transformação-no-espaço-imagem-em-r"><i class="fa fa-check"></i><b>1.2</b> Transformação no Espaço Imagem em R</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#referências-bibliográficas"><i class="fa fa-check"></i><b>1.3</b> Referências Bibliográficas</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Capítulo 06 - Transformação no Espaço Imagem</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Capítulo 06 - Transformação no Espaço Imagem</h1>
<h2 class="subtitle"><em>Processamento Digital de Imagens Orbitais</em></h2>
</div>
<div id="capítulo-06---transformação-no-espaço-imagem" class="section level1 hasAnchor" number="1" style="text-align: justify;">
<h1><span class="header-section-number">1</span> Capítulo 06 - Transformação no Espaço Imagem<a href="#capítulo-06---transformação-no-espaço-imagem" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Ref.: Cap. 10, item: 10.2: transformação por principais componentes - MENESES, P. R.; ALMEIDA, T. D.; ROSA, A. N. D. C. S.; SANO, E. E. et al. Introdução ao Processamento de Imagens de Sensoriamento Remoto. Brasília: UnB-CNPq, 276 p., 2012.</p>
<div id="introdução" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Introdução<a href="#introdução" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A análise de componentes principais (PCA, do inglês Principal Component Analysis) é uma técnica estatística que é comumente usada para redução de dimensionalidade em conjuntos de dados multivariados. Ela é útil para identificar padrões nos dados, encontrar relações entre variáveis e reduzir a complexidade dos dados, mantendo a maior quantidade possível de informações.</p>
<p>No contexto de imagens orbitais, a PCA pode ser aplicada para reduzir a dimensionalidade dos dados das imagens, permitindo uma representação mais compacta dos padrões presentes nas imagens. Isso pode ser útil para visualização, compressão de dados ou para extrair características relevantes para análises posteriores.</p>
<p>Podemos aplicar a análise de componentes principais em uma imagem com uma única banda, como uma imagem em escala de cinza. Nesse caso, cada pixel na imagem representa um valor de intensidade em uma escala de cinza, onde valores mais baixos representam tons mais escuros e valores mais altos representam tons mais claros.</p>
<p>A PCA pode ser usada para encontrar os principais modos de variabilidade nos dados da imagem, o que essencialmente significa identificar os padrões dominantes nos valores de intensidade dos pixels. Isso pode ser útil para identificar características importantes na imagem ou para reduzir a dimensionalidade dos dados enquanto se mantém a maior parte da informação relevante.</p>
<p>Ao aplicar a análise de componentes principais (PCA) a uma imagem, é importante notar que a imagem resultante pode parecer diferente da imagem original. Isso ocorre porque a PCA reorganiza os dados da imagem de forma a capturar os principais modos de variabilidade presentes nos dados, o que pode resultar em uma representação diferente da imagem original.</p>
<p>No contexto da PCA aplicada a imagens em escala de cinza, a análise identificará os padrões dominantes nos valores de intensidade dos pixels e reorganizará esses padrões de acordo com sua importância relativa. Isso pode levar a uma nova representação da imagem que ainda mantém as características essenciais, mas pode ter uma aparência diferente da imagem original.</p>
<p>Por exemplo, se a PCA for usada para reduzir a dimensionalidade dos dados da imagem, a imagem resultante pode parecer mais suavizada ou simplificada em comparação com a imagem original. Isso ocorre porque a PCA está tentando capturar a maior parte da variabilidade nos dados com um número menor de componentes principais.</p>
</div>
<div id="transformação-no-espaço-imagem-em-r" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Transformação no Espaço Imagem em R<a href="#transformação-no-espaço-imagem-em-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Na aula de hoje iremos precisar dos pacotes a seguir. Então, antes de iniciar, realizem a instalação dos pocotes e o carregamento dos mesmos, como instruído no código a seguir.</p>
<p>Antes de darmos início ao trabalho, vamos conferir se estamos trabalhando no diretório correto (pasta de trabalho).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co">#conferindo o diretório de trabalho</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
<pre><code>## [1] &quot;C:/ARQUIVOS COMPUTADOR/DOUTORADO/EBOOK PROCESSAMENTO DIGITAL DE IMAGENS&quot;</code></pre>
<p>Na prática de hoje iremos utilizar um recorte de uma imagem orbital captada da base de dados do INPE, na qual encontra-se a cidade de Franca-SP. O nome do arquivo na pasta de trabalho é <strong>franca_pan_banda4.tif</strong>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co">#Carregamento da imagem orbital</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>franca <span class="ot">&lt;-</span> <span class="fu">raster</span>(<span class="st">&quot;franca_pan_banda4.tif&quot;</span>)</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a><span class="fu">plot</span>(franca, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Recorte de Franca&quot;</span>)</span></code></pre></div>
<p><img src="cap06_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Para começar a análise de componentes principais (PCA) na imagem, precisaremos preparar os dados adequadamente. Aqui está um passo a passo básico do que precisamos fazer:</p>
<p><strong>1. Preparação dos dados:</strong> Primeiramente, vamos converter a imagem raster em um formato adequado para análise PCA, o que envolve a extração dos valores de intensidades dos pixels da imagem. Após a extração, vamos organizar estas informações em uma matriz para podermos prosseguir com a análise.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># Extraindo os valores de intensidade dos pixels</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>pixels_franca <span class="ot">&lt;-</span> <span class="fu">getValues</span>(franca)</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a><span class="co"># Organizando os valores em uma matriz</span></span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>matriz_pixels_franca <span class="ot">&lt;-</span> <span class="fu">matrix</span>(pixels_franca, <span class="at">nrow =</span> <span class="fu">ncol</span>(franca), <span class="at">ncol =</span> <span class="fu">nrow</span>(franca))</span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a><span class="co"># Transpondo a matriz para que cada linha represente um pixel</span></span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>matriz_pixels_franca <span class="ot">&lt;-</span> <span class="fu">t</span>(matriz_pixels_franca)</span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a><span class="co"># Verificando as dimensões da matriz</span></span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a><span class="fu">dim</span>(matriz_pixels_franca)</span></code></pre></div>
<pre><code>## [1] 1762 1882</code></pre>
<p>Temos uma matriz com 1762 linhas e 1882 colunas, o que significa que a imagem “franca” tem 1762 pixels de altura e 1882 pixels de largura.</p>
<p><strong>2. Normalização dos dados (opcional):</strong> Dependendo da escala dos valores de intensidade dos pixels, pode ser necessário normalizar os dados para garantir que todas as variáveis tenham a mesma escala. Isso é especialmente importante se houver grandes variações nas intensidades dos pixels. Normalizar os dados pode ser uma boa abordagem para lidar com valores ausentes e/ou infinitos e também pode ajudar a garantir que todas as variáveis tenham a mesma escala, o que é importante para a análise de PCA.Portanto, vamos normalizar os valores da matriz. No caso dos valores ausentes (NAs), faremos a substituição de NA por 0 para não prejudicar nossa análise.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># Normalizando os valores de intensidade dos pixels (0 a 1)</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>pixels_franca_normalizados <span class="ot">&lt;-</span> matriz_pixels_franca <span class="sc">/</span> <span class="dv">255</span></span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a><span class="co"># Substituindo valores NA por 0 na matriz de pixels normalizada</span></span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>pixels_franca_normalizados[<span class="fu">is.na</span>(pixels_franca_normalizados)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code></pre></div>
<p><strong>3. Aplicação da PCA:</strong> Uma vez que os dados estejam preparados e normalizados (se necessário), podemos aplicar a análise de componentes principais para extrair os principais modos de variabilidade presentes na imagem.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># Aplicando a análise de componentes principais (PCA)</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>pca_resultado_franca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(pixels_franca_normalizados)</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a><span class="co"># Verificando o resumo do resultado da PCA</span></span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a><span class="fu">summary</span>(pca_resultado_franca)</span></code></pre></div>
<pre><code>## Importance of components:
##                          PC1     PC2     PC3     PC4     PC5     PC6    PC7
## Standard deviation     2.512 1.49765 1.08677 0.97009 0.86228 0.85892 0.8027
## Proportion of Variance 0.239 0.08493 0.04472 0.03564 0.02815 0.02794 0.0244
## Cumulative Proportion  0.239 0.32397 0.36870 0.40433 0.43249 0.46042 0.4848
##                            PC8    PC9    PC10    PC11    PC12    PC13    PC14
## Standard deviation     0.72394 0.6701 0.64821 0.60780 0.56693 0.56369 0.53035
## Proportion of Variance 0.01985 0.0170 0.01591 0.01399 0.01217 0.01203 0.01065
## Cumulative Proportion  0.50467 0.5217 0.53758 0.55157 0.56374 0.57577 0.58643
##                          PC15    PC16    PC17   PC18    PC19    PC20    PC21
## Standard deviation     0.5215 0.50927 0.46600 0.4625 0.44233 0.43163 0.41258
## Proportion of Variance 0.0103 0.00982 0.00822 0.0081 0.00741 0.00705 0.00645
## Cumulative Proportion  0.5967 0.60654 0.61477 0.6229 0.63027 0.63733 0.64378
##                           PC22    PC23    PC24    PC25    PC26    PC27    PC28
## Standard deviation     0.40766 0.39975 0.39087 0.38676 0.38022 0.37842 0.36908
## Proportion of Variance 0.00629 0.00605 0.00579 0.00566 0.00547 0.00542 0.00516
## Cumulative Proportion  0.65007 0.65612 0.66190 0.66757 0.67304 0.67847 0.68362
##                          PC29    PC30    PC31    PC32    PC33    PC34    PC35
## Standard deviation     0.3559 0.35045 0.34157 0.32791 0.32729 0.31881 0.31585
## Proportion of Variance 0.0048 0.00465 0.00442 0.00407 0.00406 0.00385 0.00378
## Cumulative Proportion  0.6884 0.69307 0.69749 0.70156 0.70562 0.70946 0.71324
##                           PC36    PC37    PC38    PC39    PC40    PC41    PC42
## Standard deviation     0.30965 0.30652 0.30446 0.30143 0.29791 0.29257 0.28918
## Proportion of Variance 0.00363 0.00356 0.00351 0.00344 0.00336 0.00324 0.00317
## Cumulative Proportion  0.71687 0.72043 0.72394 0.72738 0.73074 0.73398 0.73715
##                           PC43    PC44   PC45    PC46    PC47    PC48    PC49
## Standard deviation     0.28742 0.28100 0.2769 0.27009 0.26936 0.26628 0.26136
## Proportion of Variance 0.00313 0.00299 0.0029 0.00276 0.00275 0.00268 0.00259
## Cumulative Proportion  0.74028 0.74327 0.7462 0.74893 0.75168 0.75437 0.75695
##                           PC50    PC51    PC52    PC53   PC54    PC55   PC56
## Standard deviation     0.26031 0.25773 0.25457 0.25291 0.2463 0.24472 0.2411
## Proportion of Variance 0.00257 0.00252 0.00245 0.00242 0.0023 0.00227 0.0022
## Cumulative Proportion  0.75952 0.76203 0.76449 0.76691 0.7692 0.77147 0.7737
##                           PC57    PC58   PC59    PC60    PC61    PC62    PC63
## Standard deviation     0.23860 0.23826 0.2357 0.23272 0.23078 0.22750 0.22528
## Proportion of Variance 0.00216 0.00215 0.0021 0.00205 0.00202 0.00196 0.00192
## Cumulative Proportion  0.77583 0.77798 0.7801 0.78213 0.78415 0.78611 0.78803
##                           PC64    PC65    PC66    PC67    PC68    PC69    PC70
## Standard deviation     0.22473 0.22312 0.22246 0.22138 0.21834 0.21629 0.21438
## Proportion of Variance 0.00191 0.00189 0.00187 0.00186 0.00181 0.00177 0.00174
## Cumulative Proportion  0.78995 0.79183 0.79370 0.79556 0.79737 0.79914 0.80088
##                          PC71    PC72    PC73    PC74    PC75    PC76    PC77
## Standard deviation     0.2118 0.21081 0.20825 0.20715 0.20521 0.20266 0.20124
## Proportion of Variance 0.0017 0.00168 0.00164 0.00162 0.00159 0.00156 0.00153
## Cumulative Proportion  0.8026 0.80426 0.80590 0.80753 0.80912 0.81068 0.81221
##                           PC78    PC79    PC80    PC81    PC82    PC83   PC84
## Standard deviation     0.19937 0.19825 0.19812 0.19573 0.19413 0.19289 0.1922
## Proportion of Variance 0.00151 0.00149 0.00149 0.00145 0.00143 0.00141 0.0014
## Cumulative Proportion  0.81371 0.81520 0.81669 0.81814 0.81957 0.82098 0.8224
##                           PC85    PC86    PC87    PC88   PC89    PC90    PC91
## Standard deviation     0.19116 0.18953 0.18735 0.18619 0.1855 0.18453 0.18420
## Proportion of Variance 0.00138 0.00136 0.00133 0.00131 0.0013 0.00129 0.00128
## Cumulative Proportion  0.82376 0.82512 0.82645 0.82776 0.8291 0.83035 0.83164
##                           PC92    PC93    PC94    PC95    PC96    PC97    PC98
## Standard deviation     0.18284 0.18142 0.18041 0.17966 0.17936 0.17742 0.17728
## Proportion of Variance 0.00127 0.00125 0.00123 0.00122 0.00122 0.00119 0.00119
## Cumulative Proportion  0.83290 0.83415 0.83538 0.83661 0.83782 0.83902 0.84021
##                           PC99   PC100   PC101   PC102   PC103   PC104   PC105
## Standard deviation     0.17599 0.17499 0.17281 0.17217 0.17134 0.16966 0.16877
## Proportion of Variance 0.00117 0.00116 0.00113 0.00112 0.00111 0.00109 0.00108
## Cumulative Proportion  0.84138 0.84254 0.84367 0.84479 0.84590 0.84699 0.84807
##                          PC106   PC107   PC108   PC109   PC110   PC111   PC112
## Standard deviation     0.16752 0.16683 0.16640 0.16523 0.16480 0.16399 0.16352
## Proportion of Variance 0.00106 0.00105 0.00105 0.00103 0.00103 0.00102 0.00101
## Cumulative Proportion  0.84913 0.85019 0.85124 0.85227 0.85330 0.85432 0.85533
##                         PC113   PC114   PC115   PC116   PC117   PC118   PC119
## Standard deviation     0.1623 0.16163 0.16071 0.15988 0.15890 0.15827 0.15738
## Proportion of Variance 0.0010 0.00099 0.00098 0.00097 0.00096 0.00095 0.00094
## Cumulative Proportion  0.8563 0.85732 0.85829 0.85926 0.86022 0.86117 0.86210
##                          PC120   PC121   PC122   PC123  PC124   PC125   PC126
## Standard deviation     0.15652 0.15594 0.15514 0.15465 0.1541 0.15315 0.15234
## Proportion of Variance 0.00093 0.00092 0.00091 0.00091 0.0009 0.00089 0.00088
## Cumulative Proportion  0.86303 0.86395 0.86486 0.86577 0.8667 0.86756 0.86844
##                          PC127   PC128   PC129   PC130   PC131   PC132   PC133
## Standard deviation     0.15204 0.15073 0.15048 0.14962 0.14899 0.14814 0.14786
## Proportion of Variance 0.00088 0.00086 0.00086 0.00085 0.00084 0.00083 0.00083
## Cumulative Proportion  0.86931 0.87017 0.87103 0.87188 0.87272 0.87355 0.87438
##                          PC134   PC135  PC136  PC137   PC138   PC139   PC140
## Standard deviation     0.14661 0.14613 0.1455 0.1452 0.14424 0.14343 0.14318
## Proportion of Variance 0.00081 0.00081 0.0008 0.0008 0.00079 0.00078 0.00078
## Cumulative Proportion  0.87519 0.87600 0.8768 0.8776 0.87839 0.87917 0.87994
##                          PC141   PC142   PC143   PC144   PC145   PC146   PC147
## Standard deviation     0.14253 0.14224 0.14136 0.14065 0.14018 0.13892 0.13871
## Proportion of Variance 0.00077 0.00077 0.00076 0.00075 0.00074 0.00073 0.00073
## Cumulative Proportion  0.88071 0.88148 0.88223 0.88298 0.88373 0.88446 0.88519
##                          PC148   PC149   PC150  PC151  PC152   PC153   PC154
## Standard deviation     0.13775 0.13750 0.13679 0.1362 0.1359 0.13503 0.13402
## Proportion of Variance 0.00072 0.00072 0.00071 0.0007 0.0007 0.00069 0.00068
## Cumulative Proportion  0.88591 0.88662 0.88733 0.8880 0.8887 0.88942 0.89010
##                          PC155   PC156   PC157   PC158   PC159   PC160   PC161
## Standard deviation     0.13367 0.13322 0.13275 0.13221 0.13110 0.13092 0.13046
## Proportion of Variance 0.00068 0.00067 0.00067 0.00066 0.00065 0.00065 0.00064
## Cumulative Proportion  0.89078 0.89145 0.89212 0.89278 0.89343 0.89408 0.89472
##                          PC162   PC163   PC164   PC165   PC166   PC167   PC168
## Standard deviation     0.12937 0.12906 0.12858 0.12798 0.12744 0.12707 0.12650
## Proportion of Variance 0.00063 0.00063 0.00063 0.00062 0.00062 0.00061 0.00061
## Cumulative Proportion  0.89536 0.89599 0.89661 0.89723 0.89785 0.89846 0.89907
##                         PC169  PC170   PC171   PC172   PC173   PC174   PC175
## Standard deviation     0.1263 0.1254 0.12502 0.12465 0.12442 0.12353 0.12317
## Proportion of Variance 0.0006 0.0006 0.00059 0.00059 0.00059 0.00058 0.00057
## Cumulative Proportion  0.8997 0.9003 0.90086 0.90145 0.90203 0.90261 0.90319
##                          PC176   PC177   PC178   PC179   PC180   PC181   PC182
## Standard deviation     0.12204 0.12191 0.12165 0.12104 0.12061 0.12039 0.11984
## Proportion of Variance 0.00056 0.00056 0.00056 0.00055 0.00055 0.00055 0.00054
## Cumulative Proportion  0.90375 0.90431 0.90487 0.90543 0.90598 0.90653 0.90707
##                          PC183   PC184   PC185   PC186   PC187   PC188   PC189
## Standard deviation     0.11976 0.11929 0.11856 0.11812 0.11795 0.11760 0.11700
## Proportion of Variance 0.00054 0.00054 0.00053 0.00053 0.00053 0.00052 0.00052
## Cumulative Proportion  0.90761 0.90815 0.90869 0.90921 0.90974 0.91026 0.91078
##                          PC190   PC191   PC192  PC193  PC194   PC195   PC196
## Standard deviation     0.11672 0.11623 0.11560 0.1153 0.1147 0.11425 0.11404
## Proportion of Variance 0.00052 0.00051 0.00051 0.0005 0.0005 0.00049 0.00049
## Cumulative Proportion  0.91130 0.91181 0.91232 0.9128 0.9133 0.91381 0.91430
##                          PC197   PC198   PC199   PC200   PC201   PC202   PC203
## Standard deviation     0.11353 0.11297 0.11284 0.11242 0.11202 0.11177 0.11147
## Proportion of Variance 0.00049 0.00048 0.00048 0.00048 0.00048 0.00047 0.00047
## Cumulative Proportion  0.91479 0.91528 0.91576 0.91624 0.91671 0.91718 0.91766
##                          PC204   PC205   PC206   PC207   PC208   PC209   PC210
## Standard deviation     0.11126 0.11065 0.11042 0.10996 0.10957 0.10939 0.10894
## Proportion of Variance 0.00047 0.00046 0.00046 0.00046 0.00045 0.00045 0.00045
## Cumulative Proportion  0.91812 0.91859 0.91905 0.91951 0.91996 0.92041 0.92086
##                          PC211   PC212   PC213   PC214   PC215   PC216   PC217
## Standard deviation     0.10856 0.10820 0.10793 0.10785 0.10726 0.10684 0.10641
## Proportion of Variance 0.00045 0.00044 0.00044 0.00044 0.00044 0.00043 0.00043
## Cumulative Proportion  0.92131 0.92175 0.92219 0.92264 0.92307 0.92350 0.92393
##                          PC218   PC219   PC220   PC221   PC222   PC223   PC224
## Standard deviation     0.10603 0.10539 0.10531 0.10468 0.10453 0.10429 0.10404
## Proportion of Variance 0.00043 0.00042 0.00042 0.00041 0.00041 0.00041 0.00041
## Cumulative Proportion  0.92436 0.92478 0.92520 0.92561 0.92603 0.92644 0.92685
##                          PC225  PC226  PC227  PC228   PC229   PC230   PC231
## Standard deviation     0.10363 0.1033 0.1028 0.1027 0.10208 0.10180 0.10139
## Proportion of Variance 0.00041 0.0004 0.0004 0.0004 0.00039 0.00039 0.00039
## Cumulative Proportion  0.92726 0.9277 0.9281 0.9285 0.92885 0.92925 0.92964
##                          PC232   PC233   PC234   PC235   PC236   PC237   PC238
## Standard deviation     0.10120 0.10105 0.10072 0.10044 0.09997 0.09960 0.09954
## Proportion of Variance 0.00039 0.00039 0.00038 0.00038 0.00038 0.00038 0.00038
## Cumulative Proportion  0.93002 0.93041 0.93079 0.93118 0.93156 0.93193 0.93231
##                          PC239   PC240   PC241   PC242   PC243   PC244   PC245
## Standard deviation     0.09936 0.09896 0.09864 0.09840 0.09818 0.09744 0.09706
## Proportion of Variance 0.00037 0.00037 0.00037 0.00037 0.00036 0.00036 0.00036
## Cumulative Proportion  0.93268 0.93305 0.93342 0.93379 0.93415 0.93451 0.93487
##                          PC246   PC247   PC248   PC249   PC250   PC251   PC252
## Standard deviation     0.09688 0.09676 0.09638 0.09607 0.09564 0.09514 0.09504
## Proportion of Variance 0.00036 0.00035 0.00035 0.00035 0.00035 0.00034 0.00034
## Cumulative Proportion  0.93522 0.93558 0.93593 0.93628 0.93662 0.93697 0.93731
##                          PC253   PC254   PC255   PC256   PC257   PC258   PC259
## Standard deviation     0.09454 0.09406 0.09370 0.09348 0.09332 0.09322 0.09283
## Proportion of Variance 0.00034 0.00034 0.00033 0.00033 0.00033 0.00033 0.00033
## Cumulative Proportion  0.93765 0.93798 0.93832 0.93865 0.93898 0.93931 0.93963
##                          PC260   PC261   PC262   PC263   PC264   PC265   PC266
## Standard deviation     0.09275 0.09234 0.09215 0.09156 0.09150 0.09123 0.09082
## Proportion of Variance 0.00033 0.00032 0.00032 0.00032 0.00032 0.00032 0.00031
## Cumulative Proportion  0.93996 0.94028 0.94060 0.94092 0.94124 0.94155 0.94186
##                          PC267   PC268   PC269   PC270   PC271  PC272   PC273
## Standard deviation     0.09063 0.09003 0.08992 0.08980 0.08944 0.0894 0.08897
## Proportion of Variance 0.00031 0.00031 0.00031 0.00031 0.00030 0.0003 0.00030
## Cumulative Proportion  0.94217 0.94248 0.94279 0.94309 0.94340 0.9437 0.94400
##                          PC274   PC275   PC276   PC277   PC278   PC279   PC280
## Standard deviation     0.08889 0.08851 0.08821 0.08814 0.08783 0.08745 0.08732
## Proportion of Variance 0.00030 0.00030 0.00029 0.00029 0.00029 0.00029 0.00029
## Cumulative Proportion  0.94430 0.94459 0.94489 0.94518 0.94548 0.94576 0.94605
##                          PC281   PC282   PC283   PC284   PC285   PC286   PC287
## Standard deviation     0.08704 0.08664 0.08631 0.08612 0.08604 0.08587 0.08537
## Proportion of Variance 0.00029 0.00028 0.00028 0.00028 0.00028 0.00028 0.00028
## Cumulative Proportion  0.94634 0.94662 0.94691 0.94719 0.94747 0.94775 0.94802
##                          PC288   PC289   PC290   PC291   PC292   PC293   PC294
## Standard deviation     0.08513 0.08505 0.08478 0.08431 0.08412 0.08387 0.08367
## Proportion of Variance 0.00027 0.00027 0.00027 0.00027 0.00027 0.00027 0.00027
## Cumulative Proportion  0.94830 0.94857 0.94884 0.94911 0.94938 0.94965 0.94991
##                          PC295   PC296   PC297   PC298   PC299   PC300   PC301
## Standard deviation     0.08358 0.08330 0.08300 0.08270 0.08250 0.08222 0.08193
## Proportion of Variance 0.00026 0.00026 0.00026 0.00026 0.00026 0.00026 0.00025
## Cumulative Proportion  0.95018 0.95044 0.95070 0.95096 0.95122 0.95147 0.95173
##                          PC302   PC303   PC304   PC305   PC306   PC307   PC308
## Standard deviation     0.08172 0.08139 0.08128 0.08118 0.08101 0.08050 0.08039
## Proportion of Variance 0.00025 0.00025 0.00025 0.00025 0.00025 0.00025 0.00024
## Cumulative Proportion  0.95198 0.95223 0.95248 0.95273 0.95298 0.95322 0.95347
##                          PC309   PC310   PC311   PC312   PC313   PC314   PC315
## Standard deviation     0.08015 0.07959 0.07945 0.07930 0.07914 0.07896 0.07883
## Proportion of Variance 0.00024 0.00024 0.00024 0.00024 0.00024 0.00024 0.00024
## Cumulative Proportion  0.95371 0.95395 0.95419 0.95443 0.95467 0.95490 0.95514
##                          PC316   PC317   PC318   PC319   PC320   PC321   PC322
## Standard deviation     0.07873 0.07849 0.07840 0.07804 0.07791 0.07755 0.07728
## Proportion of Variance 0.00023 0.00023 0.00023 0.00023 0.00023 0.00023 0.00023
## Cumulative Proportion  0.95537 0.95561 0.95584 0.95607 0.95630 0.95653 0.95675
##                          PC323   PC324   PC325   PC326   PC327   PC328   PC329
## Standard deviation     0.07714 0.07673 0.07658 0.07609 0.07602 0.07590 0.07577
## Proportion of Variance 0.00023 0.00022 0.00022 0.00022 0.00022 0.00022 0.00022
## Cumulative Proportion  0.95698 0.95720 0.95742 0.95764 0.95786 0.95808 0.95830
##                          PC330   PC331   PC332   PC333   PC334   PC335   PC336
## Standard deviation     0.07555 0.07532 0.07496 0.07478 0.07453 0.07444 0.07414
## Proportion of Variance 0.00022 0.00021 0.00021 0.00021 0.00021 0.00021 0.00021
## Cumulative Proportion  0.95851 0.95873 0.95894 0.95915 0.95936 0.95957 0.95978
##                          PC337   PC338   PC339   PC340  PC341   PC342   PC343
## Standard deviation     0.07409 0.07394 0.07373 0.07352 0.0731 0.07294 0.07282
## Proportion of Variance 0.00021 0.00021 0.00021 0.00020 0.0002 0.00020 0.00020
## Cumulative Proportion  0.95999 0.96020 0.96040 0.96061 0.9608 0.96101 0.96121
##                          PC344   PC345   PC346   PC347   PC348   PC349   PC350
## Standard deviation     0.07256 0.07247 0.07217 0.07211 0.07185 0.07164 0.07147
## Proportion of Variance 0.00020 0.00020 0.00020 0.00020 0.00020 0.00019 0.00019
## Cumulative Proportion  0.96141 0.96161 0.96181 0.96200 0.96220 0.96239 0.96259
##                          PC351   PC352   PC353   PC354   PC355   PC356   PC357
## Standard deviation     0.07120 0.07111 0.07088 0.07061 0.07045 0.07006 0.06989
## Proportion of Variance 0.00019 0.00019 0.00019 0.00019 0.00019 0.00019 0.00018
## Cumulative Proportion  0.96278 0.96297 0.96316 0.96335 0.96354 0.96372 0.96391
##                          PC358   PC359   PC360   PC361   PC362   PC363   PC364
## Standard deviation     0.06974 0.06963 0.06953 0.06925 0.06892 0.06879 0.06867
## Proportion of Variance 0.00018 0.00018 0.00018 0.00018 0.00018 0.00018 0.00018
## Cumulative Proportion  0.96409 0.96428 0.96446 0.96464 0.96482 0.96500 0.96518
##                          PC365   PC366   PC367   PC368   PC369   PC370   PC371
## Standard deviation     0.06832 0.06825 0.06817 0.06788 0.06762 0.06750 0.06720
## Proportion of Variance 0.00018 0.00018 0.00018 0.00017 0.00017 0.00017 0.00017
## Cumulative Proportion  0.96535 0.96553 0.96571 0.96588 0.96605 0.96623 0.96640
##                          PC372   PC373   PC374   PC375   PC376   PC377   PC378
## Standard deviation     0.06715 0.06701 0.06680 0.06676 0.06662 0.06651 0.06620
## Proportion of Variance 0.00017 0.00017 0.00017 0.00017 0.00017 0.00017 0.00017
## Cumulative Proportion  0.96657 0.96674 0.96691 0.96708 0.96724 0.96741 0.96758
##                          PC379   PC380   PC381   PC382   PC383   PC384   PC385
## Standard deviation     0.06587 0.06577 0.06566 0.06557 0.06543 0.06517 0.06506
## Proportion of Variance 0.00016 0.00016 0.00016 0.00016 0.00016 0.00016 0.00016
## Cumulative Proportion  0.96774 0.96791 0.96807 0.96823 0.96839 0.96855 0.96872
##                          PC386   PC387   PC388   PC389   PC390   PC391   PC392
## Standard deviation     0.06474 0.06457 0.06451 0.06442 0.06426 0.06402 0.06380
## Proportion of Variance 0.00016 0.00016 0.00016 0.00016 0.00016 0.00016 0.00015
## Cumulative Proportion  0.96887 0.96903 0.96919 0.96935 0.96950 0.96966 0.96981
##                          PC393   PC394   PC395   PC396   PC397   PC398   PC399
## Standard deviation     0.06371 0.06353 0.06343 0.06315 0.06311 0.06287 0.06244
## Proportion of Variance 0.00015 0.00015 0.00015 0.00015 0.00015 0.00015 0.00015
## Cumulative Proportion  0.96997 0.97012 0.97027 0.97042 0.97057 0.97072 0.97087
##                          PC400   PC401   PC402   PC403   PC404   PC405   PC406
## Standard deviation     0.06236 0.06218 0.06216 0.06190 0.06169 0.06160 0.06142
## Proportion of Variance 0.00015 0.00015 0.00015 0.00015 0.00014 0.00014 0.00014
## Cumulative Proportion  0.97102 0.97116 0.97131 0.97146 0.97160 0.97174 0.97189
##                          PC407   PC408   PC409   PC410   PC411   PC412   PC413
## Standard deviation     0.06134 0.06123 0.06102 0.06084 0.06066 0.06050 0.06045
## Proportion of Variance 0.00014 0.00014 0.00014 0.00014 0.00014 0.00014 0.00014
## Cumulative Proportion  0.97203 0.97217 0.97231 0.97245 0.97259 0.97273 0.97287
##                          PC414   PC415   PC416   PC417   PC418   PC419   PC420
## Standard deviation     0.06020 0.06015 0.05987 0.05982 0.05951 0.05944 0.05929
## Proportion of Variance 0.00014 0.00014 0.00014 0.00014 0.00013 0.00013 0.00013
## Cumulative Proportion  0.97300 0.97314 0.97328 0.97341 0.97355 0.97368 0.97381
##                          PC421   PC422   PC423   PC424   PC425   PC426   PC427
## Standard deviation     0.05923 0.05900 0.05874 0.05864 0.05851 0.05826 0.05807
## Proportion of Variance 0.00013 0.00013 0.00013 0.00013 0.00013 0.00013 0.00013
## Cumulative Proportion  0.97395 0.97408 0.97421 0.97434 0.97447 0.97460 0.97473
##                          PC428   PC429   PC430   PC431   PC432   PC433   PC434
## Standard deviation     0.05806 0.05763 0.05759 0.05756 0.05740 0.05720 0.05703
## Proportion of Variance 0.00013 0.00013 0.00013 0.00013 0.00012 0.00012 0.00012
## Cumulative Proportion  0.97485 0.97498 0.97510 0.97523 0.97535 0.97548 0.97560
##                          PC435   PC436   PC437   PC438   PC439   PC440   PC441
## Standard deviation     0.05693 0.05681 0.05659 0.05655 0.05643 0.05629 0.05621
## Proportion of Variance 0.00012 0.00012 0.00012 0.00012 0.00012 0.00012 0.00012
## Cumulative Proportion  0.97572 0.97585 0.97597 0.97609 0.97621 0.97633 0.97645
##                          PC442   PC443   PC444   PC445   PC446   PC447   PC448
## Standard deviation     0.05606 0.05588 0.05575 0.05559 0.05536 0.05528 0.05497
## Proportion of Variance 0.00012 0.00012 0.00012 0.00012 0.00012 0.00012 0.00011
## Cumulative Proportion  0.97657 0.97669 0.97680 0.97692 0.97704 0.97715 0.97727
##                          PC449   PC450   PC451   PC452   PC453   PC454   PC455
## Standard deviation     0.05489 0.05473 0.05466 0.05458 0.05438 0.05426 0.05413
## Proportion of Variance 0.00011 0.00011 0.00011 0.00011 0.00011 0.00011 0.00011
## Cumulative Proportion  0.97738 0.97749 0.97761 0.97772 0.97783 0.97794 0.97806
##                          PC456   PC457   PC458   PC459   PC460   PC461   PC462
## Standard deviation     0.05402 0.05389 0.05373 0.05368 0.05349 0.05345 0.05329
## Proportion of Variance 0.00011 0.00011 0.00011 0.00011 0.00011 0.00011 0.00011
## Cumulative Proportion  0.97817 0.97828 0.97839 0.97849 0.97860 0.97871 0.97882
##                          PC463   PC464   PC465   PC466   PC467   PC468   PC469
## Standard deviation     0.05317 0.05311 0.05294 0.05282 0.05269 0.05254 0.05239
## Proportion of Variance 0.00011 0.00011 0.00011 0.00011 0.00011 0.00010 0.00010
## Cumulative Proportion  0.97893 0.97903 0.97914 0.97924 0.97935 0.97945 0.97956
##                          PC470   PC471   PC472   PC473  PC474   PC475  PC476
## Standard deviation     0.05225 0.05206 0.05197 0.05184 0.0517 0.05165 0.0515
## Proportion of Variance 0.00010 0.00010 0.00010 0.00010 0.0001 0.00010 0.0001
## Cumulative Proportion  0.97966 0.97976 0.97987 0.97997 0.9801 0.98017 0.9803
##                          PC477   PC478   PC479  PC480   PC481   PC482   PC483
## Standard deviation     0.05133 0.05115 0.05111 0.0509 0.05072 0.05068 0.05048
## Proportion of Variance 0.00010 0.00010 0.00010 0.0001 0.00010 0.00010 0.00010
## Cumulative Proportion  0.98037 0.98047 0.98057 0.9807 0.98076 0.98086 0.98096
##                          PC484   PC485   PC486   PC487   PC488   PC489   PC490
## Standard deviation     0.05027 0.05011 0.05009 0.04997 0.04977 0.04967 0.04948
## Proportion of Variance 0.00010 0.00010 0.00010 0.00009 0.00009 0.00009 0.00009
## Cumulative Proportion  0.98105 0.98115 0.98124 0.98134 0.98143 0.98152 0.98162
##                          PC491   PC492   PC493   PC494   PC495   PC496   PC497
## Standard deviation     0.04939 0.04921 0.04911 0.04904 0.04886 0.04881 0.04877
## Proportion of Variance 0.00009 0.00009 0.00009 0.00009 0.00009 0.00009 0.00009
## Cumulative Proportion  0.98171 0.98180 0.98189 0.98198 0.98207 0.98216 0.98225
##                          PC498   PC499   PC500   PC501   PC502   PC503   PC504
## Standard deviation     0.04841 0.04831 0.04828 0.04811 0.04805 0.04790 0.04773
## Proportion of Variance 0.00009 0.00009 0.00009 0.00009 0.00009 0.00009 0.00009
## Cumulative Proportion  0.98234 0.98243 0.98252 0.98261 0.98270 0.98278 0.98287
##                          PC505   PC506   PC507   PC508   PC509   PC510   PC511
## Standard deviation     0.04755 0.04751 0.04739 0.04729 0.04710 0.04694 0.04684
## Proportion of Variance 0.00009 0.00009 0.00009 0.00008 0.00008 0.00008 0.00008
## Cumulative Proportion  0.98295 0.98304 0.98312 0.98321 0.98329 0.98338 0.98346
##                          PC512   PC513   PC514   PC515   PC516   PC517   PC518
## Standard deviation     0.04672 0.04663 0.04653 0.04641 0.04628 0.04614 0.04603
## Proportion of Variance 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008
## Cumulative Proportion  0.98354 0.98362 0.98371 0.98379 0.98387 0.98395 0.98403
##                          PC519   PC520   PC521   PC522   PC523   PC524   PC525
## Standard deviation     0.04601 0.04578 0.04575 0.04558 0.04549 0.04541 0.04526
## Proportion of Variance 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008
## Cumulative Proportion  0.98411 0.98419 0.98427 0.98435 0.98443 0.98450 0.98458
##                          PC526   PC527   PC528   PC529   PC530   PC531   PC532
## Standard deviation     0.04523 0.04513 0.04496 0.04483 0.04474 0.04462 0.04458
## Proportion of Variance 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008 0.00008
## Cumulative Proportion  0.98466 0.98474 0.98481 0.98489 0.98496 0.98504 0.98512
##                          PC533   PC534   PC535   PC536   PC537   PC538   PC539
## Standard deviation     0.04452 0.04446 0.04431 0.04423 0.04409 0.04398 0.04388
## Proportion of Variance 0.00008 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007
## Cumulative Proportion  0.98519 0.98527 0.98534 0.98541 0.98549 0.98556 0.98563
##                          PC540   PC541   PC542   PC543   PC544   PC545   PC546
## Standard deviation     0.04367 0.04354 0.04343 0.04327 0.04316 0.04307 0.04295
## Proportion of Variance 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007
## Cumulative Proportion  0.98571 0.98578 0.98585 0.98592 0.98599 0.98606 0.98613
##                          PC547   PC548   PC549   PC550   PC551   PC552   PC553
## Standard deviation     0.04291 0.04279 0.04274 0.04260 0.04257 0.04238 0.04230
## Proportion of Variance 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007
## Cumulative Proportion  0.98620 0.98627 0.98634 0.98641 0.98648 0.98654 0.98661
##                          PC554   PC555   PC556   PC557   PC558   PC559   PC560
## Standard deviation     0.04222 0.04220 0.04206 0.04198 0.04190 0.04168 0.04163
## Proportion of Variance 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007 0.00007
## Cumulative Proportion  0.98668 0.98675 0.98681 0.98688 0.98695 0.98701 0.98708
##                          PC561   PC562   PC563   PC564   PC565   PC566   PC567
## Standard deviation     0.04158 0.04144 0.04137 0.04128 0.04121 0.04114 0.04102
## Proportion of Variance 0.00007 0.00007 0.00006 0.00006 0.00006 0.00006 0.00006
## Cumulative Proportion  0.98714 0.98721 0.98727 0.98734 0.98740 0.98747 0.98753
##                          PC568   PC569   PC570   PC571   PC572   PC573   PC574
## Standard deviation     0.04089 0.04071 0.04056 0.04051 0.04042 0.04034 0.04020
## Proportion of Variance 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006
## Cumulative Proportion  0.98759 0.98766 0.98772 0.98778 0.98784 0.98790 0.98797
##                          PC575   PC576   PC577   PC578   PC579   PC580   PC581
## Standard deviation     0.04011 0.03995 0.03992 0.03983 0.03976 0.03962 0.03956
## Proportion of Variance 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006
## Cumulative Proportion  0.98803 0.98809 0.98815 0.98821 0.98827 0.98833 0.98839
##                          PC582   PC583   PC584   PC585   PC586   PC587   PC588
## Standard deviation     0.03944 0.03928 0.03924 0.03919 0.03908 0.03898 0.03893
## Proportion of Variance 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006
## Cumulative Proportion  0.98844 0.98850 0.98856 0.98862 0.98868 0.98873 0.98879
##                          PC589   PC590   PC591   PC592   PC593   PC594   PC595
## Standard deviation     0.03873 0.03869 0.03860 0.03842 0.03836 0.03834 0.03820
## Proportion of Variance 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006 0.00006
## Cumulative Proportion  0.98885 0.98891 0.98896 0.98902 0.98907 0.98913 0.98918
##                          PC596   PC597   PC598   PC599   PC600   PC601   PC602
## Standard deviation     0.03807 0.03795 0.03787 0.03780 0.03768 0.03764 0.03753
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005
## Cumulative Proportion  0.98924 0.98929 0.98935 0.98940 0.98946 0.98951 0.98956
##                          PC603   PC604   PC605   PC606   PC607   PC608   PC609
## Standard deviation     0.03744 0.03736 0.03728 0.03723 0.03717 0.03692 0.03690
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005
## Cumulative Proportion  0.98962 0.98967 0.98972 0.98977 0.98983 0.98988 0.98993
##                          PC610   PC611   PC612   PC613   PC614   PC615   PC616
## Standard deviation     0.03672 0.03667 0.03662 0.03651 0.03643 0.03631 0.03621
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005
## Cumulative Proportion  0.98998 0.99003 0.99008 0.99013 0.99018 0.99023 0.99028
##                          PC617   PC618   PC619   PC620   PC621   PC622   PC623
## Standard deviation     0.03618 0.03612 0.03602 0.03583 0.03574 0.03565 0.03562
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005
## Cumulative Proportion  0.99033 0.99038 0.99043 0.99048 0.99053 0.99058 0.99062
##                          PC624   PC625   PC626   PC627   PC628   PC629   PC630
## Standard deviation     0.03558 0.03551 0.03539 0.03525 0.03523 0.03518 0.03511
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005
## Cumulative Proportion  0.99067 0.99072 0.99077 0.99081 0.99086 0.99091 0.99095
##                          PC631   PC632   PC633   PC634   PC635   PC636   PC637
## Standard deviation     0.03501 0.03490 0.03478 0.03459 0.03458 0.03451 0.03437
## Proportion of Variance 0.00005 0.00005 0.00005 0.00005 0.00005 0.00005 0.00004
## Cumulative Proportion  0.99100 0.99105 0.99109 0.99114 0.99118 0.99123 0.99127
##                          PC638   PC639   PC640   PC641   PC642   PC643   PC644
## Standard deviation     0.03425 0.03420 0.03413 0.03402 0.03395 0.03383 0.03381
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99132 0.99136 0.99141 0.99145 0.99149 0.99154 0.99158
##                          PC645   PC646   PC647   PC648   PC649   PC650   PC651
## Standard deviation     0.03379 0.03357 0.03353 0.03345 0.03340 0.03332 0.03325
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99162 0.99167 0.99171 0.99175 0.99179 0.99184 0.99188
##                          PC652   PC653   PC654   PC655   PC656   PC657   PC658
## Standard deviation     0.03318 0.03311 0.03307 0.03296 0.03285 0.03282 0.03268
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99192 0.99196 0.99200 0.99204 0.99208 0.99212 0.99217
##                          PC659   PC660   PC661   PC662   PC663   PC664   PC665
## Standard deviation     0.03256 0.03250 0.03237 0.03229 0.03227 0.03216 0.03208
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99221 0.99225 0.99229 0.99232 0.99236 0.99240 0.99244
##                          PC666   PC667   PC668   PC669   PC670   PC671   PC672
## Standard deviation     0.03198 0.03187 0.03180 0.03178 0.03170 0.03161 0.03153
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99248 0.99252 0.99256 0.99260 0.99263 0.99267 0.99271
##                          PC673   PC674   PC675   PC676   PC677   PC678   PC679
## Standard deviation     0.03144 0.03139 0.03136 0.03123 0.03114 0.03114 0.03095
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99275 0.99278 0.99282 0.99286 0.99290 0.99293 0.99297
##                          PC680   PC681   PC682   PC683   PC684   PC685   PC686
## Standard deviation     0.03090 0.03088 0.03078 0.03069 0.03067 0.03064 0.03054
## Proportion of Variance 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004 0.00004
## Cumulative Proportion  0.99300 0.99304 0.99308 0.99311 0.99315 0.99318 0.99322
##                          PC687   PC688   PC689   PC690   PC691   PC692   PC693
## Standard deviation     0.03041 0.03036 0.03028 0.03023 0.03016 0.03003 0.02993
## Proportion of Variance 0.00004 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99325 0.99329 0.99332 0.99336 0.99339 0.99343 0.99346
##                          PC694   PC695   PC696   PC697   PC698   PC699   PC700
## Standard deviation     0.02987 0.02982 0.02974 0.02967 0.02966 0.02961 0.02955
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99349 0.99353 0.99356 0.99359 0.99363 0.99366 0.99369
##                          PC701   PC702   PC703   PC704   PC705   PC706   PC707
## Standard deviation     0.02943 0.02937 0.02931 0.02917 0.02907 0.02899 0.02898
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99373 0.99376 0.99379 0.99382 0.99386 0.99389 0.99392
##                          PC708   PC709   PC710   PC711   PC712   PC713   PC714
## Standard deviation     0.02878 0.02871 0.02866 0.02863 0.02854 0.02853 0.02849
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99395 0.99398 0.99401 0.99404 0.99408 0.99411 0.99414
##                          PC715   PC716   PC717   PC718   PC719   PC720   PC721
## Standard deviation     0.02846 0.02840 0.02828 0.02823 0.02815 0.02807 0.02806
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99417 0.99420 0.99423 0.99426 0.99429 0.99432 0.99435
##                          PC722   PC723   PC724   PC725   PC726   PC727   PC728
## Standard deviation     0.02798 0.02783 0.02776 0.02770 0.02765 0.02754 0.02752
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99438 0.99441 0.99444 0.99447 0.99449 0.99452 0.99455
##                          PC729   PC730   PC731   PC732   PC733   PC734   PC735
## Standard deviation     0.02749 0.02738 0.02731 0.02722 0.02719 0.02713 0.02709
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99458 0.99461 0.99464 0.99467 0.99469 0.99472 0.99475
##                          PC736   PC737   PC738   PC739   PC740   PC741   PC742
## Standard deviation     0.02696 0.02693 0.02688 0.02683 0.02671 0.02671 0.02659
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99478 0.99480 0.99483 0.99486 0.99489 0.99491 0.99494
##                          PC743   PC744   PC745   PC746   PC747   PC748   PC749
## Standard deviation     0.02650 0.02645 0.02641 0.02632 0.02625 0.02618 0.02613
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003 0.00003
## Cumulative Proportion  0.99497 0.99499 0.99502 0.99505 0.99507 0.99510 0.99512
##                          PC750   PC751   PC752   PC753   PC754   PC755   PC756
## Standard deviation     0.02602 0.02598 0.02592 0.02579 0.02578 0.02563 0.02558
## Proportion of Variance 0.00003 0.00003 0.00003 0.00003 0.00003 0.00002 0.00002
## Cumulative Proportion  0.99515 0.99517 0.99520 0.99522 0.99525 0.99527 0.99530
##                          PC757   PC758   PC759   PC760   PC761   PC762   PC763
## Standard deviation     0.02552 0.02547 0.02540 0.02538 0.02535 0.02532 0.02525
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99532 0.99535 0.99537 0.99540 0.99542 0.99545 0.99547
##                          PC764   PC765   PC766   PC767   PC768   PC769   PC770
## Standard deviation     0.02507 0.02503 0.02498 0.02493 0.02485 0.02478 0.02474
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99549 0.99552 0.99554 0.99557 0.99559 0.99561 0.99563
##                          PC771   PC772   PC773   PC774   PC775   PC776   PC777
## Standard deviation     0.02470 0.02467 0.02458 0.02455 0.02443 0.02438 0.02433
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99566 0.99568 0.99570 0.99573 0.99575 0.99577 0.99579
##                          PC778   PC779   PC780   PC781   PC782   PC783   PC784
## Standard deviation     0.02426 0.02417 0.02411 0.02408 0.02402 0.02398 0.02395
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99582 0.99584 0.99586 0.99588 0.99590 0.99593 0.99595
##                          PC785   PC786   PC787   PC788   PC789   PC790   PC791
## Standard deviation     0.02390 0.02384 0.02379 0.02371 0.02361 0.02356 0.02350
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99597 0.99599 0.99601 0.99603 0.99606 0.99608 0.99610
##                          PC792   PC793   PC794   PC795   PC796   PC797   PC798
## Standard deviation     0.02346 0.02338 0.02331 0.02328 0.02317 0.02309 0.02308
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99612 0.99614 0.99616 0.99618 0.99620 0.99622 0.99624
##                          PC799   PC800   PC801   PC802   PC803   PC804   PC805
## Standard deviation     0.02304 0.02301 0.02298 0.02290 0.02282 0.02280 0.02268
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99626 0.99628 0.99630 0.99632 0.99634 0.99636 0.99638
##                          PC806   PC807   PC808   PC809   PC810   PC811   PC812
## Standard deviation     0.02258 0.02258 0.02255 0.02247 0.02240 0.02238 0.02233
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99640 0.99642 0.99644 0.99646 0.99648 0.99649 0.99651
##                          PC813   PC814   PC815   PC816   PC817   PC818   PC819
## Standard deviation     0.02223 0.02215 0.02209 0.02205 0.02198 0.02192 0.02190
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99653 0.99655 0.99657 0.99659 0.99661 0.99662 0.99664
##                          PC820   PC821   PC822   PC823   PC824   PC825   PC826
## Standard deviation     0.02189 0.02186 0.02182 0.02173 0.02168 0.02165 0.02154
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99666 0.99668 0.99670 0.99671 0.99673 0.99675 0.99677
##                          PC827   PC828   PC829   PC830   PC831   PC832   PC833
## Standard deviation     0.02151 0.02146 0.02138 0.02134 0.02125 0.02117 0.02113
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99678 0.99680 0.99682 0.99684 0.99685 0.99687 0.99689
##                          PC834   PC835   PC836   PC837   PC838   PC839   PC840
## Standard deviation     0.02108 0.02103 0.02099 0.02091 0.02083 0.02080 0.02077
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99690 0.99692 0.99694 0.99695 0.99697 0.99699 0.99700
##                          PC841   PC842   PC843   PC844   PC845   PC846   PC847
## Standard deviation     0.02069 0.02067 0.02060 0.02057 0.02050 0.02047 0.02038
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99702 0.99704 0.99705 0.99707 0.99708 0.99710 0.99712
##                          PC848   PC849   PC850   PC851   PC852   PC853   PC854
## Standard deviation     0.02034 0.02030 0.02028 0.02023 0.02013 0.02010 0.02003
## Proportion of Variance 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002 0.00002
## Cumulative Proportion  0.99713 0.99715 0.99716 0.99718 0.99719 0.99721 0.99722
##                          PC855   PC856   PC857   PC858   PC859   PC860   PC861
## Standard deviation     0.01999 0.01989 0.01983 0.01979 0.01977 0.01970 0.01965
## Proportion of Variance 0.00002 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99724 0.99725 0.99727 0.99728 0.99730 0.99731 0.99733
##                          PC862   PC863   PC864   PC865   PC866   PC867   PC868
## Standard deviation     0.01963 0.01953 0.01952 0.01947 0.01939 0.01938 0.01935
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99734 0.99736 0.99737 0.99739 0.99740 0.99741 0.99743
##                          PC869   PC870   PC871   PC872   PC873   PC874   PC875
## Standard deviation     0.01931 0.01925 0.01919 0.01913 0.01910 0.01906 0.01899
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99744 0.99746 0.99747 0.99748 0.99750 0.99751 0.99753
##                          PC876   PC877   PC878   PC879   PC880   PC881   PC882
## Standard deviation     0.01894 0.01888 0.01884 0.01877 0.01870 0.01868 0.01862
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99754 0.99755 0.99757 0.99758 0.99759 0.99761 0.99762
##                          PC883   PC884   PC885   PC886   PC887   PC888   PC889
## Standard deviation     0.01859 0.01853 0.01847 0.01844 0.01842 0.01834 0.01832
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99763 0.99764 0.99766 0.99767 0.99768 0.99770 0.99771
##                          PC890   PC891   PC892   PC893   PC894   PC895   PC896
## Standard deviation     0.01827 0.01823 0.01817 0.01814 0.01804 0.01799 0.01795
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99772 0.99773 0.99775 0.99776 0.99777 0.99778 0.99780
##                          PC897   PC898   PC899   PC900   PC901   PC902   PC903
## Standard deviation     0.01793 0.01788 0.01782 0.01775 0.01773 0.01766 0.01765
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99781 0.99782 0.99783 0.99784 0.99786 0.99787 0.99788
##                          PC904   PC905   PC906   PC907   PC908   PC909   PC910
## Standard deviation     0.01760 0.01753 0.01750 0.01749 0.01747 0.01742 0.01739
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99789 0.99790 0.99791 0.99793 0.99794 0.99795 0.99796
##                          PC911   PC912   PC913   PC914   PC915   PC916   PC917
## Standard deviation     0.01734 0.01724 0.01720 0.01718 0.01714 0.01712 0.01707
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99797 0.99798 0.99799 0.99801 0.99802 0.99803 0.99804
##                          PC918   PC919   PC920   PC921   PC922   PC923   PC924
## Standard deviation     0.01705 0.01701 0.01699 0.01693 0.01685 0.01682 0.01679
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99805 0.99806 0.99807 0.99808 0.99809 0.99810 0.99811
##                          PC925   PC926   PC927   PC928   PC929   PC930   PC931
## Standard deviation     0.01670 0.01666 0.01665 0.01662 0.01658 0.01652 0.01646
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99813 0.99814 0.99815 0.99816 0.99817 0.99818 0.99819
##                          PC932   PC933   PC934   PC935   PC936   PC937   PC938
## Standard deviation     0.01643 0.01637 0.01634 0.01629 0.01626 0.01622 0.01619
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99820 0.99821 0.99822 0.99823 0.99824 0.99825 0.99826
##                          PC939   PC940   PC941   PC942   PC943   PC944   PC945
## Standard deviation     0.01616 0.01606 0.01603 0.01594 0.01592 0.01590 0.01587
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99827 0.99828 0.99829 0.99830 0.99831 0.99832 0.99833
##                          PC946   PC947   PC948   PC949   PC950   PC951   PC952
## Standard deviation     0.01581 0.01576 0.01572 0.01566 0.01562 0.01556 0.01549
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99834 0.99834 0.99835 0.99836 0.99837 0.99838 0.99839
##                          PC953   PC954   PC955   PC956   PC957   PC958   PC959
## Standard deviation     0.01549 0.01547 0.01542 0.01535 0.01533 0.01529 0.01525
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99840 0.99841 0.99842 0.99843 0.99844 0.99844 0.99845
##                          PC960   PC961   PC962   PC963   PC964   PC965   PC966
## Standard deviation     0.01521 0.01520 0.01518 0.01515 0.01513 0.01507 0.01500
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99846 0.99847 0.99848 0.99849 0.99850 0.99851 0.99851
##                          PC967   PC968   PC969   PC970   PC971   PC972   PC973
## Standard deviation     0.01498 0.01493 0.01488 0.01485 0.01482 0.01480 0.01474
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99852 0.99853 0.99854 0.99855 0.99856 0.99856 0.99857
##                          PC974   PC975   PC976   PC977   PC978   PC979   PC980
## Standard deviation     0.01471 0.01468 0.01461 0.01459 0.01454 0.01451 0.01448
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99858 0.99859 0.99860 0.99861 0.99861 0.99862 0.99863
##                          PC981   PC982   PC983   PC984   PC985   PC986   PC987
## Standard deviation     0.01441 0.01439 0.01436 0.01432 0.01426 0.01420 0.01419
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99864 0.99865 0.99865 0.99866 0.99867 0.99868 0.99868
##                          PC988   PC989   PC990   PC991   PC992   PC993   PC994
## Standard deviation     0.01414 0.01410 0.01407 0.01405 0.01402 0.01400 0.01392
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99869 0.99870 0.99871 0.99871 0.99872 0.99873 0.99874
##                          PC995   PC996   PC997   PC998   PC999  PC1000  PC1001
## Standard deviation     0.01384 0.01380 0.01374 0.01373 0.01372 0.01366 0.01365
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99874 0.99875 0.99876 0.99876 0.99877 0.99878 0.99879
##                         PC1002  PC1003  PC1004  PC1005  PC1006  PC1007  PC1008
## Standard deviation     0.01363 0.01361 0.01355 0.01351 0.01345 0.01344 0.01342
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99879 0.99880 0.99881 0.99881 0.99882 0.99883 0.99883
##                         PC1009  PC1010  PC1011  PC1012  PC1013  PC1014  PC1015
## Standard deviation     0.01337 0.01334 0.01333 0.01327 0.01324 0.01322 0.01318
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99884 0.99885 0.99885 0.99886 0.99887 0.99887 0.99888
##                         PC1016  PC1017  PC1018  PC1019  PC1020  PC1021  PC1022
## Standard deviation     0.01317 0.01309 0.01309 0.01305 0.01301 0.01295 0.01292
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99889 0.99889 0.99890 0.99891 0.99891 0.99892 0.99893
##                         PC1023  PC1024  PC1025  PC1026  PC1027  PC1028  PC1029
## Standard deviation     0.01288 0.01287 0.01283 0.01281 0.01280 0.01277 0.01273
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99893 0.99894 0.99894 0.99895 0.99896 0.99896 0.99897
##                         PC1030  PC1031  PC1032  PC1033  PC1034  PC1035  PC1036
## Standard deviation     0.01269 0.01262 0.01257 0.01255 0.01253 0.01247 0.01246
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99898 0.99898 0.99899 0.99899 0.99900 0.99901 0.99901
##                         PC1037  PC1038  PC1039  PC1040  PC1041  PC1042  PC1043
## Standard deviation     0.01244 0.01241 0.01233 0.01232 0.01228 0.01224 0.01218
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99902 0.99902 0.99903 0.99903 0.99904 0.99905 0.99905
##                         PC1044  PC1045  PC1046  PC1047  PC1048  PC1049  PC1050
## Standard deviation     0.01217 0.01211 0.01208 0.01206 0.01199 0.01195 0.01193
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99906 0.99906 0.99907 0.99907 0.99908 0.99908 0.99909
##                         PC1051  PC1052  PC1053  PC1054  PC1055  PC1056  PC1057
## Standard deviation     0.01191 0.01189 0.01184 0.01181 0.01180 0.01175 0.01172
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99910 0.99910 0.99911 0.99911 0.99912 0.99912 0.99913
##                         PC1058  PC1059  PC1060  PC1061  PC1062  PC1063  PC1064
## Standard deviation     0.01169 0.01169 0.01167 0.01164 0.01160 0.01158 0.01152
## Proportion of Variance 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
## Cumulative Proportion  0.99913 0.99914 0.99914 0.99915 0.99915 0.99916 0.99916
##                         PC1065  PC1066  PC1067  PC1068  PC1069  PC1070  PC1071
## Standard deviation     0.01151 0.01149 0.01143 0.01139 0.01138 0.01136 0.01132
## Proportion of Variance 0.00001 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
## Cumulative Proportion  0.99917 0.99917 0.99918 0.99918 0.99919 0.99919 0.99920
##                         PC1072  PC1073  PC1074  PC1075  PC1076  PC1077  PC1078
## Standard deviation     0.01126 0.01125 0.01123 0.01116 0.01115 0.01114 0.01109
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
## Cumulative Proportion  0.99920 0.99921 0.99921 0.99922 0.99922 0.99923 0.99923
##                         PC1079  PC1080  PC1081  PC1082  PC1083  PC1084 PC1085
## Standard deviation     0.01108 0.01105 0.01102 0.01099 0.01096 0.01092 0.0109
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000
## Cumulative Proportion  0.99924 0.99924 0.99924 0.99925 0.99925 0.99926 0.9993
##                         PC1086  PC1087  PC1088  PC1089  PC1090  PC1091  PC1092
## Standard deviation     0.01088 0.01083 0.01082 0.01079 0.01075 0.01073 0.01067
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
## Cumulative Proportion  0.99927 0.99927 0.99928 0.99928 0.99928 0.99929 0.99929
##                         PC1093  PC1094  PC1095  PC1096  PC1097  PC1098  PC1099
## Standard deviation     0.01064 0.01061 0.01058 0.01056 0.01054 0.01049 0.01049
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
## Cumulative Proportion  0.99930 0.99930 0.99931 0.99931 0.99931 0.99932 0.99932
##                         PC1100  PC1101  PC1102  PC1103  PC1104 PC1105  PC1106
## Standard deviation     0.01042 0.01041 0.01038 0.01036 0.01035 0.0103 0.01028
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000 0.00000
## Cumulative Proportion  0.99933 0.99933 0.99934 0.99934 0.99934 0.9993 0.99935
##                         PC1107  PC1108  PC1109  PC1110  PC1111 PC1112  PC1113
## Standard deviation     0.01026 0.01025 0.01018 0.01015 0.01011 0.0101 0.01008
## Proportion of Variance 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000 0.00000
## Cumulative Proportion  0.99936 0.99936 0.99936 0.99937 0.99937 0.9994 0.99938
##                         PC1114  PC1115  PC1116   PC1117   PC1118   PC1119
## Standard deviation     0.01006 0.01004 0.01001 0.009958 0.009925 0.009901
## Proportion of Variance 0.00000 0.00000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99938 0.99939 0.99939 0.999390 0.999400 0.999400
##                          PC1120   PC1121   PC1122   PC1123   PC1124   PC1125
## Standard deviation     0.009872 0.009847 0.009819 0.009789 0.009776 0.009741
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999410 0.999410 0.999410 0.999420 0.999420 0.999420
##                          PC1126   PC1127   PC1128   PC1129   PC1130   PC1131
## Standard deviation     0.009724 0.009695 0.009663 0.009639 0.009607 0.009586
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999430 0.999430 0.999430 0.999440 0.999440 0.999440
##                          PC1132   PC1133   PC1134   PC1135   PC1136   PC1137
## Standard deviation     0.009534 0.009525 0.009511 0.009473 0.009426 0.009392
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999450 0.999450 0.999450 0.999460 0.999460 0.999460
##                          PC1138   PC1139   PC1140   PC1141   PC1142   PC1143
## Standard deviation     0.009368 0.009359 0.009327 0.009305 0.009291 0.009272
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999470 0.999470 0.999470 0.999480 0.999480 0.999480
##                          PC1144   PC1145   PC1146   PC1147   PC1148  PC1149
## Standard deviation     0.009235 0.009225 0.009172 0.009145 0.009116 0.00907
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999490 0.999490 0.999490 0.999500 0.999500 0.99950
##                          PC1150   PC1151   PC1152  PC1153   PC1154   PC1155
## Standard deviation     0.009068 0.009062 0.009034 0.00902 0.008996 0.008968
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999510 0.999510 0.999510 0.99952 0.999520 0.999520
##                          PC1156   PC1157   PC1158   PC1159  PC1160   PC1161
## Standard deviation     0.008934 0.008924 0.008893 0.008867 0.00884 0.008822
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  0.999530 0.999530 0.999530 0.999530 0.99954 0.999540
##                          PC1162   PC1163   PC1164   PC1165   PC1166  PC1167
## Standard deviation     0.008784 0.008753 0.008725 0.008722 0.008699 0.00866
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999540 0.999550 0.999550 0.999550 0.999550 0.99956
##                          PC1168   PC1169   PC1170   PC1171   PC1172   PC1173
## Standard deviation     0.008645 0.008618 0.008582 0.008572 0.008542 0.008525
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999560 0.999560 0.999570 0.999570 0.999570 0.999570
##                          PC1174   PC1175   PC1176   PC1177   PC1178   PC1179
## Standard deviation     0.008495 0.008457 0.008435 0.008403 0.008374 0.008354
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999580 0.999580 0.999580 0.999580 0.999590 0.999590
##                          PC1180   PC1181   PC1182   PC1183   PC1184   PC1185
## Standard deviation     0.008305 0.008297 0.008281 0.008256 0.008224 0.008199
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999590 0.999600 0.999600 0.999600 0.999600 0.999610
##                          PC1186   PC1187   PC1188  PC1189   PC1190   PC1191
## Standard deviation     0.008169 0.008169 0.008152 0.00813 0.008107 0.008096
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999610 0.999610 0.999610 0.99962 0.999620 0.999620
##                         PC1192  PC1193   PC1194   PC1195   PC1196   PC1197
## Standard deviation     0.00805 0.00804 0.008008 0.007984 0.007967 0.007952
## Proportion of Variance 0.00000 0.00000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99962 0.99963 0.999630 0.999630 0.999630 0.999640
##                          PC1198  PC1199   PC1200   PC1201   PC1202  PC1203
## Standard deviation     0.007907 0.00788 0.007867 0.007848 0.007842 0.00782
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999640 0.99964 0.999640 0.999640 0.999650 0.99965
##                          PC1204   PC1205   PC1206   PC1207   PC1208   PC1209
## Standard deviation     0.007791 0.007771 0.007735 0.007724 0.007718 0.007668
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999650 0.999650 0.999660 0.999660 0.999660 0.999660
##                          PC1210   PC1211   PC1212   PC1213   PC1214   PC1215
## Standard deviation     0.007638 0.007629 0.007588 0.007578 0.007553 0.007526
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999670 0.999670 0.999670 0.999670 0.999670 0.999680
##                          PC1216   PC1217   PC1218   PC1219   PC1220   PC1221
## Standard deviation     0.007499 0.007465 0.007436 0.007413 0.007394 0.007383
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999680 0.999680 0.999680 0.999680 0.999690 0.999690
##                          PC1222   PC1223   PC1224   PC1225  PC1226  PC1227
## Standard deviation     0.007336 0.007331 0.007307 0.007287 0.00728 0.00727
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.00000
## Cumulative Proportion  0.999690 0.999690 0.999690 0.999700 0.99970 0.99970
##                         PC1228   PC1229 PC1230   PC1231   PC1232   PC1233
## Standard deviation     0.00725 0.007224 0.0072 0.007186 0.007163 0.007135
## Proportion of Variance 0.00000 0.000000 0.0000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99970 0.999700 0.9997 0.999710 0.999710 0.999710
##                          PC1234   PC1235  PC1236   PC1237   PC1238   PC1239
## Standard deviation     0.007113 0.007096 0.00707 0.007058 0.007036 0.007019
## Proportion of Variance 0.000000 0.000000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999710 0.999720 0.99972 0.999720 0.999720 0.999720
##                          PC1240   PC1241   PC1242   PC1243   PC1244   PC1245
## Standard deviation     0.006979 0.006967 0.006939 0.006933 0.006913 0.006875
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999730 0.999730 0.999730 0.999730 0.999730 0.999730
##                          PC1246   PC1247   PC1248   PC1249   PC1250   PC1251
## Standard deviation     0.006858 0.006844 0.006832 0.006823 0.006786 0.006774
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999740 0.999740 0.999740 0.999740 0.999740 0.999750
##                          PC1252  PC1253   PC1254   PC1255   PC1256   PC1257
## Standard deviation     0.006763 0.00674 0.006718 0.006695 0.006667 0.006643
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999750 0.99975 0.999750 0.999750 0.999750 0.999760
##                          PC1258   PC1259   PC1260  PC1261   PC1262   PC1263
## Standard deviation     0.006623 0.006608 0.006598 0.00657 0.006556 0.006536
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999760 0.999760 0.999760 0.99976 0.999760 0.999770
##                          PC1264   PC1265   PC1266   PC1267   PC1268   PC1269
## Standard deviation     0.006524 0.006513 0.006499 0.006485 0.006466 0.006439
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999770 0.999770 0.999770 0.999770 0.999770 0.999770
##                          PC1270   PC1271   PC1272  PC1273   PC1274   PC1275
## Standard deviation     0.006424 0.006406 0.006378 0.00636 0.006326 0.006307
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999780 0.999780 0.999780 0.99978 0.999780 0.999780
##                          PC1276   PC1277   PC1278   PC1279   PC1280   PC1281
## Standard deviation     0.006287 0.006277 0.006265 0.006254 0.006223 0.006213
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999790 0.999790 0.999790 0.999790 0.999790 0.999790
##                         PC1282   PC1283  PC1284  PC1285   PC1286   PC1287
## Standard deviation     0.00621 0.006188 0.00615 0.00612 0.006116 0.006111
## Proportion of Variance 0.00000 0.000000 0.00000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.99979 0.999800 0.99980 0.99980 0.999800 0.999800
##                          PC1288   PC1289   PC1290   PC1291   PC1292  PC1293
## Standard deviation     0.006076 0.006071 0.006059 0.005996 0.005993 0.00598
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999800 0.999800 0.999810 0.999810 0.999810 0.99981
##                          PC1294   PC1295   PC1296  PC1297   PC1298   PC1299
## Standard deviation     0.005967 0.005952 0.005934 0.00591 0.005898 0.005866
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999810 0.999810 0.999810 0.99982 0.999820 0.999820
##                          PC1300   PC1301   PC1302   PC1303   PC1304   PC1305
## Standard deviation     0.005863 0.005837 0.005815 0.005802 0.005788 0.005774
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999820 0.999820 0.999820 0.999820 0.999820 0.999830
##                          PC1306   PC1307  PC1308   PC1309   PC1310   PC1311
## Standard deviation     0.005752 0.005744 0.00573 0.005718 0.005698 0.005689
## Proportion of Variance 0.000000 0.000000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999830 0.999830 0.99983 0.999830 0.999830 0.999830
##                          PC1312   PC1313   PC1314   PC1315   PC1316   PC1317
## Standard deviation     0.005665 0.005631 0.005623 0.005611 0.005579 0.005559
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999830 0.999840 0.999840 0.999840 0.999840 0.999840
##                          PC1318   PC1319   PC1320   PC1321   PC1322   PC1323
## Standard deviation     0.005542 0.005526 0.005509 0.005491 0.005473 0.005455
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999840 0.999840 0.999840 0.999840 0.999850 0.999850
##                          PC1324   PC1325   PC1326   PC1327   PC1328   PC1329
## Standard deviation     0.005444 0.005404 0.005399 0.005392 0.005366 0.005352
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999850 0.999850 0.999850 0.999850 0.999850 0.999850
##                          PC1330   PC1331   PC1332   PC1333   PC1334   PC1335
## Standard deviation     0.005331 0.005325 0.005305 0.005296 0.005279 0.005269
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999850 0.999860 0.999860 0.999860 0.999860 0.999860
##                          PC1336   PC1337   PC1338   PC1339   PC1340   PC1341
## Standard deviation     0.005255 0.005229 0.005227 0.005204 0.005181 0.005175
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999860 0.999860 0.999860 0.999860 0.999870 0.999870
##                          PC1342   PC1343   PC1344   PC1345   PC1346   PC1347
## Standard deviation     0.005171 0.005144 0.005131 0.005116 0.005112 0.005075
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999870 0.999870 0.999870 0.999870 0.999870 0.999870
##                         PC1348   PC1349   PC1350   PC1351   PC1352   PC1353
## Standard deviation     0.00506 0.005057 0.005045 0.005028 0.005005 0.004996
## Proportion of Variance 0.00000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99987 0.999870 0.999870 0.999880 0.999880 0.999880
##                          PC1354   PC1355   PC1356   PC1357   PC1358   PC1359
## Standard deviation     0.004973 0.004955 0.004931 0.004916 0.004904 0.004895
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999880 0.999880 0.999880 0.999880 0.999880 0.999880
##                          PC1360  PC1361   PC1362   PC1363   PC1364   PC1365
## Standard deviation     0.004881 0.00487 0.004859 0.004832 0.004818 0.004803
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999880 0.99989 0.999890 0.999890 0.999890 0.999890
##                          PC1366   PC1367   PC1368   PC1369   PC1370   PC1371
## Standard deviation     0.004795 0.004787 0.004772 0.004739 0.004731 0.004713
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999890 0.999890 0.999890 0.999890 0.999890 0.999890
##                          PC1372   PC1373   PC1374   PC1375   PC1376   PC1377
## Standard deviation     0.004699 0.004697 0.004676 0.004662 0.004647 0.004634
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999890 0.999900 0.999900 0.999900 0.999900 0.999900
##                         PC1378   PC1379   PC1380   PC1381   PC1382   PC1383
## Standard deviation     0.00463 0.004597 0.004593 0.004592 0.004578 0.004549
## Proportion of Variance 0.00000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99990 0.999900 0.999900 0.999900 0.999900 0.999900
##                          PC1384   PC1385   PC1386  PC1387   PC1388   PC1389
## Standard deviation     0.004536 0.004527 0.004511 0.00449 0.004477 0.004453
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999900 0.999910 0.999910 0.99991 0.999910 0.999910
##                          PC1390   PC1391  PC1392   PC1393   PC1394   PC1395
## Standard deviation     0.004445 0.004434 0.00443 0.004425 0.004405 0.004397
## Proportion of Variance 0.000000 0.000000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999910 0.999910 0.99991 0.999910 0.999910 0.999910
##                         PC1396   PC1397   PC1398   PC1399   PC1400   PC1401
## Standard deviation     0.00437 0.004346 0.004334 0.004311 0.004304 0.004287
## Proportion of Variance 0.00000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99991 0.999910 0.999910 0.999920 0.999920 0.999920
##                          PC1402   PC1403  PC1404   PC1405   PC1406  PC1407
## Standard deviation     0.004269 0.004259 0.00425 0.004236 0.004231 0.00421
## Proportion of Variance 0.000000 0.000000 0.00000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999920 0.999920 0.99992 0.999920 0.999920 0.99992
##                          PC1408   PC1409   PC1410   PC1411  PC1412   PC1413
## Standard deviation     0.004202 0.004182 0.004174 0.004158 0.00415 0.004139
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  0.999920 0.999920 0.999920 0.999920 0.99992 0.999920
##                          PC1414   PC1415   PC1416   PC1417   PC1418   PC1419
## Standard deviation     0.004106 0.004089 0.004083 0.004071 0.004055 0.004047
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999930 0.999930 0.999930 0.999930 0.999930 0.999930
##                          PC1420   PC1421   PC1422   PC1423   PC1424   PC1425
## Standard deviation     0.004032 0.004012 0.004008 0.003992 0.003973 0.003969
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999930 0.999930 0.999930 0.999930 0.999930 0.999930
##                          PC1426   PC1427   PC1428  PC1429   PC1430   PC1431
## Standard deviation     0.003952 0.003946 0.003944 0.00392 0.003893 0.003885
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999930 0.999930 0.999930 0.99993 0.999940 0.999940
##                          PC1432   PC1433   PC1434   PC1435   PC1436   PC1437
## Standard deviation     0.003872 0.003863 0.003845 0.003839 0.003825 0.003809
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999940 0.999940 0.999940 0.999940 0.999940 0.999940
##                          PC1438  PC1439   PC1440  PC1441   PC1442   PC1443
## Standard deviation     0.003799 0.00377 0.003761 0.00375 0.003744 0.003729
## Proportion of Variance 0.000000 0.00000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999940 0.99994 0.999940 0.99994 0.999940 0.999940
##                          PC1444   PC1445   PC1446   PC1447   PC1448   PC1449
## Standard deviation     0.003716 0.003701 0.003694 0.003686 0.003666 0.003661
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999940 0.999940 0.999940 0.999940 0.999940 0.999950
##                          PC1450   PC1451   PC1452   PC1453   PC1454   PC1455
## Standard deviation     0.003628 0.003625 0.003616 0.003608 0.003579 0.003574
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999950 0.999950 0.999950 0.999950 0.999950 0.999950
##                          PC1456   PC1457   PC1458   PC1459   PC1460   PC1461
## Standard deviation     0.003574 0.003551 0.003547 0.003528 0.003513 0.003509
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999950 0.999950 0.999950 0.999950 0.999950 0.999950
##                          PC1462   PC1463   PC1464  PC1465   PC1466  PC1467
## Standard deviation     0.003486 0.003481 0.003475 0.00346 0.003434 0.00343
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.00000
## Cumulative Proportion  0.999950 0.999950 0.999950 0.99995 0.999950 0.99995
##                          PC1468   PC1469   PC1470   PC1471   PC1472   PC1473
## Standard deviation     0.003414 0.003399 0.003386 0.003372 0.003352 0.003346
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999950 0.999950 0.999960 0.999960 0.999960 0.999960
##                          PC1474   PC1475   PC1476   PC1477   PC1478   PC1479
## Standard deviation     0.003334 0.003326 0.003305 0.003302 0.003294 0.003279
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999960 0.999960 0.999960 0.999960 0.999960 0.999960
##                          PC1480   PC1481   PC1482   PC1483   PC1484   PC1485
## Standard deviation     0.003265 0.003262 0.003244 0.003227 0.003218 0.003202
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999960 0.999960 0.999960 0.999960 0.999960 0.999960
##                          PC1486  PC1487   PC1488   PC1489  PC1490   PC1491
## Standard deviation     0.003192 0.00318 0.003165 0.003158 0.00315 0.003146
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  0.999960 0.99996 0.999960 0.999960 0.99996 0.999960
##                          PC1492   PC1493   PC1494   PC1495   PC1496   PC1497
## Standard deviation     0.003128 0.003117 0.003105 0.003089 0.003081 0.003066
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999960 0.999960 0.999960 0.999970 0.999970 0.999970
##                          PC1498   PC1499   PC1500   PC1501  PC1502   PC1503
## Standard deviation     0.003058 0.003047 0.003045 0.003014 0.00301 0.003006
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  0.999970 0.999970 0.999970 0.999970 0.99997 0.999970
##                          PC1504   PC1505   PC1506   PC1507   PC1508   PC1509
## Standard deviation     0.002987 0.002981 0.002973 0.002949 0.002939 0.002925
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999970 0.999970 0.999970 0.999970 0.999970 0.999970
##                          PC1510   PC1511 PC1512   PC1513   PC1514   PC1515
## Standard deviation     0.002912 0.002908 0.0029 0.002881 0.002874 0.002865
## Proportion of Variance 0.000000 0.000000 0.0000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999970 0.999970 1.0000 0.999970 0.999970 0.999970
##                          PC1516  PC1517  PC1518   PC1519   PC1520   PC1521
## Standard deviation     0.002851 0.00284 0.00282 0.002807 0.002794 0.002784
## Proportion of Variance 0.000000 0.00000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999970 0.99997 0.99997 0.999970 0.999970 0.999970
##                          PC1522   PC1523   PC1524   PC1525   PC1526  PC1527
## Standard deviation     0.002774 0.002767 0.002759 0.002748 0.002738 0.00273
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999970 0.999970 0.999970 0.999970 0.999980 0.99998
##                          PC1528   PC1529   PC1530  PC1531   PC1532   PC1533
## Standard deviation     0.002724 0.002708 0.002689 0.00267 0.002663 0.002652
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.99998 0.999980 0.999980
##                          PC1534   PC1535   PC1536   PC1537 PC1538   PC1539
## Standard deviation     0.002643 0.002636 0.002628 0.002615 0.0026 0.002578
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.0000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.999980 1.0000 0.999980
##                          PC1540  PC1541   PC1542   PC1543   PC1544  PC1545
## Standard deviation     0.002576 0.00257 0.002559 0.002548 0.002536 0.00253
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999980 0.99998 0.999980 0.999980 0.999980 0.99998
##                          PC1546   PC1547   PC1548   PC1549   PC1550   PC1551
## Standard deviation     0.002523 0.002511 0.002502 0.002482 0.002468 0.002457
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.999980 0.999980 0.999980
##                          PC1552   PC1553   PC1554   PC1555   PC1556   PC1557
## Standard deviation     0.002447 0.002439 0.002422 0.002418 0.002405 0.002389
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.999980 0.999980 0.999980
##                          PC1558   PC1559   PC1560   PC1561   PC1562   PC1563
## Standard deviation     0.002376 0.002369 0.002366 0.002361 0.002345 0.002343
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.999980 0.999980 0.999980
##                          PC1564   PC1565   PC1566   PC1567   PC1568   PC1569
## Standard deviation     0.002329 0.002303 0.002294 0.002291 0.002286 0.002275
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999980 0.999980 0.999980 0.999980 0.999980 0.999990
##                         PC1570   PC1571   PC1572   PC1573   PC1574   PC1575
## Standard deviation     0.00226 0.002258 0.002241 0.002232 0.002227 0.002208
## Proportion of Variance 0.00000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.99999 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1576   PC1577   PC1578   PC1579   PC1580   PC1581
## Standard deviation     0.002189 0.002186 0.002178 0.002166 0.002149 0.002142
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1582   PC1583   PC1584   PC1585   PC1586   PC1587
## Standard deviation     0.002128 0.002123 0.002112 0.002101 0.002094 0.002083
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1588   PC1589   PC1590   PC1591   PC1592   PC1593
## Standard deviation     0.002076 0.002067 0.002053 0.002036 0.002029 0.002015
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1594   PC1595   PC1596   PC1597   PC1598   PC1599
## Standard deviation     0.002005 0.001991 0.001986 0.001977 0.001964 0.001959
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1600   PC1601   PC1602   PC1603   PC1604   PC1605
## Standard deviation     0.001951 0.001944 0.001932 0.001926 0.001912 0.001901
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1606   PC1607   PC1608   PC1609  PC1610   PC1611
## Standard deviation     0.001895 0.001883 0.001869 0.001845 0.00184 0.001837
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.99999 0.999990
##                          PC1612   PC1613   PC1614   PC1615   PC1616   PC1617
## Standard deviation     0.001831 0.001813 0.001807 0.001794 0.001787 0.001785
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1618   PC1619   PC1620   PC1621   PC1622   PC1623
## Standard deviation     0.001771 0.001756 0.001752 0.001744 0.001738 0.001731
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.999990
##                          PC1624   PC1625   PC1626   PC1627   PC1628  PC1629
## Standard deviation     0.001722 0.001709 0.001703 0.001694 0.001683 0.00168
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.00000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 0.999990 0.99999
##                          PC1630  PC1631   PC1632   PC1633   PC1634   PC1635
## Standard deviation     0.001655 0.00164 0.001635 0.001623 0.001612 0.001609
## Proportion of Variance 0.000000 0.00000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.99999 0.999990 0.999990 0.999990 0.999990
##                          PC1636   PC1637   PC1638   PC1639   PC1640   PC1641
## Standard deviation     0.001599 0.001587 0.001575 0.001569 0.001563 0.001558
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  0.999990 0.999990 0.999990 0.999990 1.000000 1.000000
##                          PC1642   PC1643   PC1644   PC1645  PC1646   PC1647
## Standard deviation     0.001547 0.001525 0.001518 0.001512 0.00151 0.001498
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.00000 1.000000
##                          PC1648   PC1649   PC1650   PC1651   PC1652   PC1653
## Standard deviation     0.001487 0.001478 0.001457 0.001453 0.001435 0.001426
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.000000 1.000000
##                         PC1654   PC1655   PC1656   PC1657   PC1658   PC1659
## Standard deviation     0.00142 0.001416 0.001411 0.001395 0.001389 0.001375
## Proportion of Variance 0.00000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.00000 1.000000 1.000000 1.000000 1.000000 1.000000
##                          PC1660   PC1661   PC1662   PC1663  PC1664   PC1665
## Standard deviation     0.001364 0.001358 0.001347 0.001341 0.00132 0.001311
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.00000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.00000 1.000000
##                          PC1666   PC1667   PC1668   PC1669   PC1670   PC1671
## Standard deviation     0.001299 0.001295 0.001291 0.001281 0.001275 0.001263
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.000000 1.000000
##                          PC1672   PC1673   PC1674   PC1675   PC1676   PC1677
## Standard deviation     0.001252 0.001235 0.001232 0.001217 0.001216 0.001207
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.000000 1.000000
##                          PC1678   PC1679   PC1680  PC1681   PC1682   PC1683
## Standard deviation     0.001202 0.001198 0.001186 0.00118 0.001172 0.001163
## Proportion of Variance 0.000000 0.000000 0.000000 0.00000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.00000 1.000000 1.000000
##                          PC1684   PC1685  PC1686   PC1687   PC1688   PC1689
## Standard deviation     0.001152 0.001146 0.00113 0.001115 0.001112 0.001107
## Proportion of Variance 0.000000 0.000000 0.00000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.00000 1.000000 1.000000 1.000000
##                          PC1690   PC1691   PC1692   PC1693   PC1694   PC1695
## Standard deviation     0.001088 0.001084 0.001083 0.001076 0.001066 0.001061
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.000000 1.000000
##                          PC1696   PC1697   PC1698   PC1699   PC1700    PC1701
## Standard deviation     0.001054 0.001036 0.001024 0.001013 0.001008 0.0009983
## Proportion of Variance 0.000000 0.000000 0.000000 0.000000 0.000000 0.0000000
## Cumulative Proportion  1.000000 1.000000 1.000000 1.000000 1.000000 1.0000000
##                           PC1702    PC1703    PC1704   PC1705    PC1706
## Standard deviation     0.0009853 0.0009824 0.0009771 0.000953 0.0009517
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.000000 1.0000000
##                           PC1707    PC1708    PC1709   PC1710   PC1711
## Standard deviation     0.0009364 0.0009353 0.0009265 0.000918 0.000912
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.000000 0.000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.000000 1.000000
##                           PC1712    PC1713    PC1714    PC1715    PC1716
## Standard deviation     0.0008928 0.0008869 0.0008827 0.0008778 0.0008608
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1717   PC1718    PC1719    PC1720    PC1721
## Standard deviation     0.0008581 0.000841 0.0008242 0.0008173 0.0008107
## Proportion of Variance 0.0000000 0.000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.000000 1.0000000 1.0000000 1.0000000
##                          PC1722    PC1723    PC1724    PC1725    PC1726
## Standard deviation     0.000799 0.0007922 0.0007884 0.0007742 0.0007631
## Proportion of Variance 0.000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1727    PC1728    PC1729    PC1730    PC1731
## Standard deviation     0.0007601 0.0007483 0.0007339 0.0007274 0.0007142
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1732    PC1733    PC1734   PC1735   PC1736
## Standard deviation     0.0007044 0.0007011 0.0006929 0.000684 0.000674
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.000000 0.000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.000000 1.000000
##                           PC1737    PC1738    PC1739    PC1740    PC1741
## Standard deviation     0.0006701 0.0006565 0.0006511 0.0006283 0.0006177
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1742    PC1743    PC1744    PC1745    PC1746
## Standard deviation     0.0006129 0.0005976 0.0005742 0.0005711 0.0005678
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1747    PC1748    PC1749    PC1750    PC1751
## Standard deviation     0.0005453 0.0005404 0.0005195 0.0005116 0.0004966
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1752    PC1753   PC1754    PC1755    PC1756
## Standard deviation     0.0004839 0.0004722 0.000456 0.0004392 0.0004354
## Proportion of Variance 0.0000000 0.0000000 0.000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.000000 1.0000000 1.0000000
##                           PC1757    PC1758    PC1759    PC1760    PC1761
## Standard deviation     0.0004314 0.0004173 0.0003785 0.0003657 0.0003095
## Proportion of Variance 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
## Cumulative Proportion  1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
##                           PC1762
## Standard deviation     1.116e-15
## Proportion of Variance 0.000e+00
## Cumulative Proportion  1.000e+00</code></pre>
<p>O resumo apresentado pela função <em>summary()</em> é muito extenso, mas ele mostra a importância das componentes princiais (PCs) na explicação da variância dos dados. Cada PC tem um valor associado, que indica quanto da variância total dos dados ele explica. Neste contexto, podemos selecionar um número adequado de PCs com base na quantidade de variância que desejamos reter nos dados. Por exemplo, se quisermos reter 95% da variância total, podemos escolher as primeiras PCs que acumulam 95% da variância.</p>
<p>Para reter 95% da variância total na análise, podemos calcular a proporção da variância explicada por cada componente principal e selecionar as primeiras PCs que acumulam 95% da variância. Seguiremos os seguintes passos:</p>
<ol style="list-style-type: lower-alpha">
<li>Calcularemos os autovalores resultantes da análise PCA;</li>
<li>Dividiremos cada autovalor pelo total da soma dos autovalores para obter a proporção da variância explicada por cada PC;</li>
<li>Calcularemos a proporção cumulativa de variância acumulada;</li>
<li>Determinaremos quantas PCs são necessárias para acumluar pelo menos 95% da variância total.</li>
</ol>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># Calcula a proporção de variância explicada por cada PC</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>variance_proportion <span class="ot">&lt;-</span> pca_resultado_franca<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(pca_resultado_franca<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a><span class="co"># Calcula a proporção cumulativa de variância explicada</span></span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a>cumulative_variance <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(variance_proportion)</span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a><span class="co"># Determina quantas PCs são necessárias para reter 95% da variância</span></span>
<span id="cb9-8"><a href="#cb9-8" tabindex="-1"></a>n_components <span class="ot">&lt;-</span> <span class="fu">which</span>(cumulative_variance <span class="sc">&gt;=</span> <span class="fl">0.95</span>)[<span class="dv">1</span>]</span>
<span id="cb9-9"><a href="#cb9-9" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" tabindex="-1"></a><span class="co"># Exibe o resultado</span></span>
<span id="cb9-11"><a href="#cb9-11" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Numero de componentes necessarias para reter 95% da variancia:&quot;</span>, n_components))</span></code></pre></div>
<pre><code>## [1] &quot;Numero de componentes necessarias para reter 95% da variancia: 295&quot;</code></pre>
<p>De acordo com o resultado, sabemos que precisamos de 295 componentes principais para reter 95% da variância. Assim, podemos proceder com a redução da dimensionalidade, mantendo apenas esses componentes; isso nos ajudará a simplificar a representação dos dados, mantendo a maior parte da informação relevante. Vamos prosseguir com o código para realizar a redução da dimensionalidade.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># Reduzindo a dimensionalidade mantendo os 295 primeiros componentes principais</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>pca_reduzido_franca <span class="ot">&lt;-</span> pca_resultado_franca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">295</span>]</span></code></pre></div>
<p>Após reduzir a dimensionalidade, o próximo passo é reconstruir a imagem usando os componentes principais reduzidos. Podemos fazer isso multiplicando a matriz dos componentes principais reduzidos pelos vetores próprios correspondentes e adicionando a média, se a média dos dados foi subtraída durante o processo de PCA. Essa ação nos dará uma aproximação da imagem original, mas com uma dimensionalidade reduzida. O código a seguir demonstra essa operação.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># Reconstruindo a imagem usando os componentes principais reduzidos</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>imagem_reconstruida <span class="ot">&lt;-</span> pca_reduzido_franca <span class="sc">%*%</span> <span class="fu">t</span>(pca_resultado_franca<span class="sc">$</span>rotation[, <span class="dv">1</span><span class="sc">:</span><span class="dv">295</span>])</span></code></pre></div>
<p>No código acima, a reconstrução da imagem é feita utilizando os componentes principais reduzidos (pca_reduzido_franca) e a matriz de rotação dos componentes principais (pca_resultado_franca$rotation[, 1:295]). Detalhando cada um dos aspectos:</p>
<ul>
<li><p>pca_reduzido_franca: Esta é a matriz contendo os dados reduzidos para as dimensões escolhidas (neste caso, os 295 primeiros componentes principais). Cada linha dessa matriz representa um ponto de dados, e cada coluna representa uma dimensão reduzida.</p></li>
<li><p>pca_resultado_franca$rotation[, 1:295]: Esta é a matriz de rotação dos componentes principais. Ela contém os vetores de peso que são usados para transformar os dados originais em dados nos novos espaços de características definidos pelos componentes principais. Aqui, estamos selecionando apenas as primeiras 295 colunas, que correspondem aos primeiros 295 componentes principais.</p></li>
<li><p>%*%: Este é o operador de multiplicação de matrizes em R. Ele realiza a multiplicação matricial entre pca_reduzido_franca e a transposta da matriz de rotação.</p></li>
<li><p>t(pca_resultado_franca$rotation[, 1:295]): Este trecho transpõe a matriz de rotação para garantir que as dimensões estejam alinhadas corretamente para a multiplicação.</p></li>
<li><p>imagem_reconstruida: Esta é a matriz resultante da multiplicação, que representa a imagem reconstruída no novo espaço de características definido pelos componentes principais.</p></li>
</ul>
<p>Basicamente, multiplicamos os dados reduzidos pelos componentes principais pela transposta da matriz de rotação para reconstruir a imagem original a partir dos componentes principais reduzidos. Isso nos permite visualizar como a imagem se parece quando projetada no espaço de características definido pelos primeiros 295 componentes principais.</p>
<p>Agora vamos conferir se a matriz de <strong>imagem_reconstruida</strong> possui as mesmas dimensões da nossa <strong>matriz_pixels_franca</strong>, utilizando a função <em>dim()</em>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="fu">dim</span>(matriz_pixels_franca)</span></code></pre></div>
<pre><code>## [1] 1762 1882</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="fu">dim</span>(imagem_reconstruida)</span></code></pre></div>
<pre><code>## [1] 1762 1882</code></pre>
<p>Os resultados demonstraram que a <strong>imagem_reconstruida</strong> possui a mesma dimensão de <strong>matriz_pixels_franca.</strong> Diante disso, podemos prosseguir com a reconstrução de fato da nossa imagem orbital, agora com os componentes principais reduzidos. Para reconstrução podemos usar a função <em>raster()</em>, criando uma imagem a partir da matriz <strong>imagem_reconstruida</strong>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="co"># Criando uma imagem raster a partir da matriz reconstruída</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>imagem_reconstruida_raster <span class="ot">&lt;-</span> <span class="fu">raster</span>(<span class="fu">matrix</span>(imagem_reconstruida, <span class="at">ncol =</span> <span class="fu">ncol</span>(imagem_reconstruida)))</span></code></pre></div>
<p>Após a reconstrução da nossa imagem, vamos comparar nossa imagem original de Franca e a imagem com componentes principais reduzidos.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># Plotar comparativamente a imagem original de Franca e a imagem com componentes principais reduzidos</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a><span class="fu">plot</span>(franca, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Recorte de Franca&quot;</span>)</span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a><span class="fu">plot</span>(imagem_reconstruida_raster, <span class="at">col =</span> <span class="fu">gray.colors</span>(<span class="dv">256</span>), <span class="at">main =</span> <span class="st">&quot;Imagem PCA&quot;</span>)</span></code></pre></div>
<p><img src="cap06_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Comparativamente, observamos que a imagem com os componentes principais reduzidos mostra-se mais suavizada frente a imagem original de Franca, ou seja, verificamos que houve uma redução das intensidades colorimétricas que definem limites na área da imagem original.</p>
<p>Com isso, encerramos a prática de hoje sobre Transformação no Espaço Imagem, demonstrando a construção do código para a análise de principais componentes, reduzindo os valores colorimétricos através desta estrutura analítica e gerando uma imagem com os componentes principais reduzidos. Nos vemos na próxima aula.</p>
<p><a href="apresentação.html">Índice</a></p>
<p><a href="capítulo-05---morfologia-matemática.html">Capítulo 05 - Morfologia Matemática</a></p>
<p><a href="capítulo-07---aritmética-de-bandas-soma-subtração-multiplicação-e-divisão.html">Capítulo 07 - Aritmética de Bandas: soma, subtração, multiplicação e divisão</a></p>
</div>
<div id="referências-bibliográficas" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Referências Bibliográficas<a href="#referências-bibliográficas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ANDERSON, E. C. Making Maps with R Â: Reproducible Research. GitHub, 2021. Disponível em: <a href="https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html" class="uri">https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html</a>.</p>
<p>CHAMBERS, J. M. Extending R. CRC Press, 364p., 2017. ISBN: 9781498775724.</p>
<p>DA SILVA, F. R.; GONÇALVES-SOUZA, T.; PATERNO, G. B.; PROVETE, D. B.; VANCINE, M. H. Análises ecológicas no R. Recife, PE: Nupeea, 1ª ed., 640p., 2022. ISBN: 9788579175640. Disponível em: <a href="https://analises-ecologicas.com/" class="uri">https://analises-ecologicas.com/</a>.</p>
<p>GAUTHIER, N. Anthromes 12K DGG (V1) analysis code and R research compendium. Harvard Dataverse, 2021. DOI: <a href="https://doi.org/10.7910/DVN/6FWPZ9" class="uri">https://doi.org/10.7910/DVN/6FWPZ9</a>.</p>
<p>LOVELACE, R. Introduction to visualizing spatial data in R. 2017. Disponível em:<a href="https://github.com/Robinlovelace/Creating-maps-in-R" class="uri">https://github.com/Robinlovelace/Creating-maps-in-R</a>.</p>
<p>LOVELACE, R., NOWOSAD, J., &amp; MUENCHOW, J. Geocomputation with R. Chapman and Hall/CRC, 353p., 2019. Disponível em: <a href="https://www.routledge.com/Geocomputation-withR/Lovelace-Nowosad-Muenchow/p/book/9780367670573" class="uri">https://www.routledge.com/Geocomputation-withR/Lovelace-Nowosad-Muenchow/p/book/9780367670573</a></p>
<p>MACHLIS, S. Create maps in R in 10 (fairly) easy steps. Computerworld, 2017. Disponível em: <a href="https://www.computerworld.com/article/3038270/create-maps-in-r-in-10-fairly-easy-steps.html" class="uri">https://www.computerworld.com/article/3038270/create-maps-in-r-in-10-fairly-easy-steps.html</a>.</p>
<p>MARTOS, G. Cluster Analysis with R. 2021. Disponível em: <a href="https://rstudio-pubsstatic.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html" class="uri">https://rstudio-pubsstatic.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html</a>.</p>
<p>MENESES, P. R.; ALMEIDA, T. D.; ROSA, A. N. D. C. S.; SANO, E. E. et al. Introdução ao Processamento de Imagens de Sensoriamento Remoto. Brasília: UnB-CNPq, 276 p., 2012.</p>
<p>MORENO, M. &amp; BASILLE, M. Drawing beautiful maps programmatically with R, sf and ggplot2 - Part 1: Basics. 2021. Disponível em: <a href="https://r-spatial.org/r/2018/10/25/ggplot2-sf.html" class="uri">https://r-spatial.org/r/2018/10/25/ggplot2-sf.html</a>.</p>
<p>MUENCHOW, J.; SCHRATZ, P.; BRENNING, A. RQGIS: Integrating R with QGIS for Statistical Geocomputing. The R Journal, 9, n. 2, p. 409-428, 2017 2017. Doi: <a href="https://doi.org/10.32614/RJ-2017-067" class="uri">https://doi.org/10.32614/RJ-2017-067</a>.</p>
<p>NOVIA, D. Cluster Analysis in R: Tips for Great Analysis and Visualization. Datanovia, 2018.Disponível em: <a href="https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/" class="uri">https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/</a>.</p>
<p>PEBESMA, E.; BIVAND, R. Spatial Data Science: With Applications in R. Chapman and Hall/CRC, 1ª ed., 314p., 2023. Doi: <a href="https://doi.org/10.1201/9780429459016" class="uri">https://doi.org/10.1201/9780429459016</a>.</p>
<p>R-BLOGGERS. Cluster Analysis in R. 2021. Disponível em: <a href="https://www.rbloggers.com/2021/04/cluster-analysis-in-r/" class="uri">https://www.rbloggers.com/2021/04/cluster-analysis-in-r/</a>.</p>
<p>STANIAK, M.; BIECEK, P. The Landscape of R Packages for Automated Exploratory Data Analysis. The R Journal, v. 11, n. 2, 23 p., 2019. Disponível em: <a href="https://arxiv.org/pdf/1904.02101" class="uri">https://arxiv.org/pdf/1904.02101</a>.</p>
<p>VENABLES, W. N.; SMITH, D. M. An Introduction to R. R Core Team, 2017. Disponível em: <a href="http://colinfay.me/intro-to-r/#" class="uri">http://colinfay.me/intro-to-r/#</a>.</p>
<p>WICKHAM, H. Advanced R. CRC Press, 2ª ed., 2022. Disponível em: <a href="https://advr.hadley.nz/#license" class="uri">https://advr.hadley.nz/#license</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
